# Generated by Django 5.2.6 on 2025-10-17 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchwabToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Short-lived OAuth access token (typically 30 minutes)"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        help_text="Long-lived refresh token (typically 7 days)"
                    ),
                ),
                (
                    "access_expires_at",
                    models.BigIntegerField(
                        help_text="Unix timestamp when access token expires"
                    ),
                ),
                (
                    "schwab_account_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary Schwab account ID (if available)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Thor user who owns this Schwab connection",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schwab_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schwab OAuth Token",
                "verbose_name_plural": "Schwab OAuth Tokens",
                "db_table": "schwab_token",
            },
        ),
    ]
