# Generated by ChatGPT on 2025-12-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SchwabToken",
            new_name="BrokerConnection",
        ),
        migrations.AlterModelOptions(
            name="brokerconnection",
            options={
                "verbose_name": "Broker Connection",
                "verbose_name_plural": "Broker Connections",
            },
        ),
        migrations.AlterModelTable(
            name="brokerconnection",
            table="broker_connection",
        ),
        migrations.AddField(
            model_name="brokerconnection",
            name="broker",
            field=models.CharField(
                choices=[("SCHWAB", "Charles Schwab")],
                default="SCHWAB",
                help_text="Broker identifier (e.g. SCHWAB)",
                max_length=32,
            ),
        ),
        migrations.RenameField(
            model_name="brokerconnection",
            old_name="schwab_account_id",
            new_name="broker_account_id",
        ),
        migrations.AlterField(
            model_name="brokerconnection",
            name="user",
            field=models.ForeignKey(
                help_text="Thor user who owns this broker connection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="brokerconnection",
            constraint=models.UniqueConstraint(
                fields=("user", "broker"),
                name="unique_user_broker_connection",
            ),
        ),
    ]
