# Generated by Django 5.2.6 on 2025-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0003_brokerconnection_trading_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerconnection",
            name="broker_account_id",
            field=models.CharField(
                blank=True,
                help_text="Primary broker account ID (if cached)",
                max_length=64,
            ),
        ),
    ]
