# Generated by Copilot
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('SchwabLiveData', '0004_alter_brokerconnection_broker_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchwabSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Canonical symbol (e.g., NVDA, /ES, SPX)', max_length=64)),
                (
                    'asset_type',
                    models.CharField(
                        choices=[('EQUITY', 'Equity'), ('FUTURE', 'Future'), ('INDEX', 'Index')],
                        default='EQUITY',
                        help_text='Asset class used to route to the proper Schwab streaming service',
                        max_length=16,
                    ),
                ),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Owner of this Schwab streaming subscription',
                        on_delete=models.CASCADE,
                        related_name='schwab_subscriptions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'schwab_subscription',
                'verbose_name': 'Schwab Subscription',
                'verbose_name_plural': 'Schwab Subscriptions',
            },
        ),
        migrations.AddConstraint(
            model_name='schwabsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'symbol', 'asset_type'), name='uniq_schwab_subscription_user_symbol_asset'),
        ),
        migrations.AddIndex(
            model_name='schwabsubscription',
            index=models.Index(fields=['user', 'asset_type'], name='idx_schwab_sub_user_asset'),
        ),
        migrations.AddIndex(
            model_name='schwabsubscription',
            index=models.Index(fields=['symbol'], name='idx_schwab_sub_symbol'),
        ),
    ]
