# Generated by Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchwabLiveData', '0005_schwabsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schwabsubscription',
            name='asset_type',
            field=models.CharField(
                choices=[
                    ('EQUITY', 'Equity'),
                    ('FUTURE', 'Future'),
                    ('INDEX', 'Index'),
                    ('OPTION', 'Option'),
                    ('BOND', 'Bond'),
                    ('FOREX', 'Forex'),
                    ('MUTUAL_FUND', 'Mutual Fund'),
                ],
                default='EQUITY',
                help_text='Asset class used to route to the proper Schwab streaming service',
                max_length=16,
            ),
        ),
    ]
