# Generated by Django 5.2.6 on 2025-12-03 19:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstrumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("color_primary", models.CharField(default="#4CAF50", max_length=7)),
                ("color_secondary", models.CharField(default="#81C784", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Instrument Category",
                "verbose_name_plural": "Instrument Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Rolling52WeekStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Trading symbol (YM, ES, NQ, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "high_52w",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Highest price in last 52 weeks",
                        max_digits=12,
                    ),
                ),
                (
                    "high_52w_date",
                    models.DateField(help_text="Date when 52w high was set"),
                ),
                (
                    "low_52w",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lowest price in last 52 weeks",
                        max_digits=12,
                    ),
                ),
                (
                    "low_52w_date",
                    models.DateField(help_text="Date when 52w low was set"),
                ),
                (
                    "last_price_checked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Most recent LAST price that was checked",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "all_time_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="All-time high (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "all_time_high_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when all-time high was set",
                        null=True,
                    ),
                ),
                (
                    "all_time_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="All-time low (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "all_time_low_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when all-time low was set",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "52-Week Stats",
                "verbose_name_plural": "52-Week Stats",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="SignalWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("STRONG_BUY", "Strong Buy"),
                            ("BUY", "Buy"),
                            ("HOLD", "Hold"),
                            ("SELL", "Sell"),
                            ("STRONG_SELL", "Strong Sell"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        help_text="Weight value for this signal type (e.g., 2, 1, 0, -1, -2)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Signal Weight",
                "verbose_name_plural": "Signal Weights",
                "ordering": ["-weight"],
            },
        ),
        migrations.CreateModel(
            name="TargetHighLowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Trading symbol (YM, ES, NQ, RTY, CL, SI, HG, GC, VX, DX, ZB)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("POINTS", "Points"),
                            ("PERCENT", "Percent"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="POINTS",
                        help_text="Computation mode: Points adds/subtracts fixed amounts; Percent uses percentage offsets; Disabled skips target calculation.",
                        max_length=10,
                    ),
                ),
                (
                    "offset_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute points above entry (BUY target / SELL stop)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "offset_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute points below entry (BUY stop / SELL target)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "percent_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent above entry (e.g. 0.50 = +0.50%)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "percent_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent below entry (e.g. 0.50 = -0.50%)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate without deleting. If inactive or disabled, capture falls back to legacy default if no other config exists.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Target High/Low Config",
                "verbose_name_plural": "Target High/Low Configs",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="FutureTrading24Hour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_group",
                    models.CharField(
                        db_index=True,
                        help_text="Shared key with MarketSession.capture_group",
                        max_length=32,
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                ("country", models.CharField(max_length=32)),
                ("future", models.CharField(max_length=20)),
                (
                    "prev_close_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_price_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_prev_diff_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_prev_pct_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "low_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "high_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "range_diff_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "range_pct_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "close_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cumulative volume across JP→US window",
                        null=True,
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False, help_text="True when US close is reached"
                    ),
                ),
            ],
            options={
                "verbose_name": "24-Hour Global Session",
                "verbose_name_plural": "24-Hour Global Sessions",
                "indexes": [
                    models.Index(
                        fields=["session_date", "country", "future"],
                        name="ThorTrading_session_6fb660_idx",
                    )
                ],
                "unique_together": {("session_group", "future")},
            },
        ),
        migrations.CreateModel(
            name="MarketSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_number",
                    models.IntegerField(help_text="Trade counter/sequence number"),
                ),
                (
                    "capture_group",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Group identifier for all rows captured in the same market-open event",
                        null=True,
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("date", models.IntegerField(help_text="Day of month")),
                (
                    "day",
                    models.CharField(
                        help_text="Day of week (Mon, Tue, etc.)", max_length=10
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Exact timestamp of capture",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Market region (Japan, China, Europe, USA, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "future",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TOTAL", "TOTAL Composite"),
                            ("YM", "Dow Jones (YM)"),
                            ("ES", "S&P 500 (ES)"),
                            ("NQ", "NASDAQ (NQ)"),
                            ("RTY", "Russell 2000 (RTY)"),
                            ("CL", "Crude Oil (CL)"),
                            ("SI", "Silver (SI)"),
                            ("HG", "Copper (HG)"),
                            ("GC", "Gold (GC)"),
                            ("VX", "Volatility (VX)"),
                            ("DX", "Dollar Index (DX)"),
                            ("ZB", "Bonds (ZB)"),
                        ],
                        help_text="Future symbol for this capture row",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "country_future",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Numeric country future metric kept next to future for ordering",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        blank=True, help_text="Weight value (for TOTAL)", null=True
                    ),
                ),
                (
                    "bhs",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("STRONG_BUY", "Strong Buy"),
                            ("SELL", "Sell"),
                            ("STRONG_SELL", "Strong Sell"),
                            ("HOLD", "Hold"),
                        ],
                        help_text="Signal from TOTAL or individual future",
                        max_length=20,
                    ),
                ),
                (
                    "wndw",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WORKED", "Worked"),
                            ("DIDNT_WORK", "Didn't Work"),
                            ("NEUTRAL", "Neutral"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        help_text="Window/outcome label (Worked / Didn't Work / Neutral / Pending)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country_future_wndw_total",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Historical total count for this country/future window",
                        null=True,
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Bid price at capture",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "bid_size",
                    models.IntegerField(blank=True, help_text="Bid size", null=True),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Last traded price at market open",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "close_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Global 24h close for this session (set at US close)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Bid-Ask spread",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "ask_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Ask price at capture",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "ask_size",
                    models.IntegerField(blank=True, help_text="Ask size", null=True),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Actual entry (Ask if buying, Bid if selling)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "target_hit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Price at which the first target or stop was hit",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "target_hit_type",
                    models.CharField(
                        blank=True,
                        choices=[("TARGET", "Profit Target"), ("STOP", "Stop Loss")],
                        help_text="Which level was hit first: profit TARGET or STOP",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "target_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Configurable target above entry (per TargetHighLowConfig)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "target_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Configurable stop below entry (per TargetHighLowConfig)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "target_hit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the first target or stop was hit",
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.BigIntegerField(
                        blank=True, help_text="Trading volume", null=True
                    ),
                ),
                (
                    "market_open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Market open move (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_high_open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="High move from open (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_high_pct_open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="High move from open (percent)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_low_open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Low move from open (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_low_pct_open",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Low move from open (percent)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Close move from open (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "session_volume",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cumulative volume while this market is OPEN",
                        null=True,
                    ),
                ),
                (
                    "market_high_pct_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent distance from intraday high",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_low_pct_close",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent distance above intraday low",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_close_vs_open_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Close vs open change (percent)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_range",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Intraday range (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "market_range_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Intraday range (percent)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "prev_close_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Previous 24h close price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "open_price_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current 24h open price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "open_prev_diff_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h Open − Prev 24h Close (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "open_prev_pct_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h Open − Prev 24h Close (%)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "low_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24 hour low",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "high_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24 hour high",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "range_diff_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h range difference (High - Low)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "range_pct_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h range as % of previous close",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "low_52w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="52-week low",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "low_pct_52w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent above 52-week low relative to current price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "high_52w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="52-week high",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "high_pct_52w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent below 52-week high relative to current price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "range_52w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="52-week range (High - Low)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "range_pct_52w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="52-week range as % of current price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "weighted_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="TOTAL weighted average (e.g., -0.109)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "instrument_count",
                    models.IntegerField(
                        blank=True,
                        default=11,
                        help_text="Count of instruments (for TOTAL)",
                        null=True,
                    ),
                ),
                (
                    "strong_buy_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Strong buy signals that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_buy_worked_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of strong buys that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_buy_didnt_work",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Strong buy signals that did not work",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_buy_didnt_work_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of strong buys that failed",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "buy_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Buy signals that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "buy_worked_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of buys that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "buy_didnt_work",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Buy signals that did not work",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "buy_didnt_work_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of buys that failed",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "hold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Hold signals count",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_sell_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Strong sell signals that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_sell_worked_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of strong sells that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_sell_didnt_work",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Strong sell signals that failed",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "strong_sell_didnt_work_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of strong sells that failed",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "sell_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sell signals that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "sell_worked_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of sells that worked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "sell_didnt_work",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Sell signals that failed",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "sell_didnt_work_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent of sells that failed",
                        max_digits=14,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Session",
                "verbose_name_plural": "Market Sessions",
                "ordering": ["-captured_at", "future"],
                "unique_together": {("country", "year", "month", "date", "future")},
            },
        ),
        migrations.CreateModel(
            name="TradingInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("exchange", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_watchlist", models.BooleanField(default=False)),
                ("show_in_ribbon", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("display_precision", models.IntegerField(default=2)),
                (
                    "tick_size",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "contract_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tick_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dollar value per tick/point movement",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "margin_requirement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Margin required per contract in USD",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("api_provider", models.CharField(blank=True, max_length=50)),
                ("api_symbol", models.CharField(blank=True, max_length=100)),
                ("update_frequency", models.IntegerField(default=5)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("is_market_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="ThorTrading.instrumentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Instrument",
                "verbose_name_plural": "Trading Instruments",
                "ordering": ["sort_order", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="ContractWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.0"), max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_weight",
                        to="ThorTrading.tradinginstrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Weight",
                "verbose_name_plural": "Contract Weights",
                "ordering": ["instrument__symbol"],
            },
        ),
        migrations.CreateModel(
            name="VwapMinute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "timestamp_minute",
                    models.DateTimeField(help_text="UTC minute (floored)"),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "cumulative_volume",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cumulative volume from feed at sample time",
                        null=True,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp_minute", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp_minute"],
                        name="ThorTrading_symbol_e939f0_idx",
                    )
                ],
                "unique_together": {("symbol", "timestamp_minute")},
            },
        ),
        migrations.CreateModel(
            name="MarketIntraday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_minute",
                    models.DateTimeField(
                        db_index=True, help_text="Minute bucket (UTC)"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Market region (e.g., USA, JPN, LON)", max_length=10
                    ),
                ),
                (
                    "future",
                    models.CharField(
                        help_text="Future symbol (e.g., ES, YM, NQ)", max_length=10
                    ),
                ),
                (
                    "market_code",
                    models.CharField(
                        help_text="Market code (e.g., USA, JPN, LON)", max_length=10
                    ),
                ),
                ("open_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("high_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("low_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("close_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("volume_1m", models.BigIntegerField()),
                (
                    "bid_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ask_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "spread_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "twentyfour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intraday_bars",
                        to="ThorTrading.futuretrading24hour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Intraday Bar",
                "verbose_name_plural": "Market Intraday Bars",
                "indexes": [
                    models.Index(
                        fields=["twentyfour"], name="ThorTrading_twentyf_37b3ab_idx"
                    )
                ],
                "unique_together": {("timestamp_minute", "future", "country")},
            },
        ),
        migrations.CreateModel(
            name="SignalStatValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("STRONG_BUY", "Strong Buy"),
                            ("BUY", "Buy"),
                            ("HOLD", "Hold"),
                            ("SELL", "Sell"),
                            ("STRONG_SELL", "Strong Sell"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=6, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_stat_values",
                        to="ThorTrading.tradinginstrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal Statistical Value",
                "verbose_name_plural": "Signal Statistical Values",
                "ordering": ["instrument__symbol", "signal"],
                "unique_together": {("instrument", "signal")},
            },
        ),
    ]
