# Generated by Django 5.2.6 on 2025-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketintraday",
            name="country",
            field=models.CharField(
                help_text="Market region (e.g., USA, JPN, LON)", max_length=32
            ),
        ),
    ]
