# Generated by Django 5.2.6 on 2025-10-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0002_delete_dataproviderconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HbsThresholds",
        ),
    ]
