# Generated by Django 5.2.6 on 2025-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0002_alter_marketintraday_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketintraday",
            name="ask_last",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="bid_last",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="close_1m",
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="future",
            field=models.CharField(
                help_text="Future symbol (e.g., ES, YM, NQ)", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="high_1m",
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="low_1m",
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="market_code",
            field=models.CharField(
                help_text="Market code (e.g., USA, JPN, LON)", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="open_1m",
            field=models.DecimalField(decimal_places=4, max_digits=32),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="spread_last",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=32, null=True
            ),
        ),
    ]
