# Generated by Django 5.2.6 on 2025-12-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0004_remove_marketintraday_market_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futuretrading24hour",
            name="country",
            field=models.CharField(
                choices=[
                    ("USA", "USA"),
                    ("Pre_USA", "Pre_USA"),
                    ("China", "China"),
                    ("Japan", "Japan"),
                    ("United Kingdom", "United Kingdom"),
                    ("India", "India"),
                ],
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="country",
            field=models.CharField(
                choices=[
                    ("USA", "USA"),
                    ("Pre_USA", "Pre_USA"),
                    ("China", "China"),
                    ("Japan", "Japan"),
                    ("United Kingdom", "United Kingdom"),
                    ("India", "India"),
                ],
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
    ]
