# Generated by Django 5.2.6 on 2025-10-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0004_remove_unused_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradingsignal",
            name="instrument",
        ),
        migrations.AlterUniqueTogether(
            name="watchlistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="group",
        ),
        migrations.RemoveField(
            model_name="watchlistitem",
            name="instrument",
        ),
        migrations.AddField(
            model_name="tradinginstrument",
            name="margin_requirement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Margin required per contract in USD",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tradinginstrument",
            name="tick_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Dollar value per tick/point movement",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="MarketData",
        ),
        migrations.DeleteModel(
            name="TradingSignal",
        ),
        migrations.DeleteModel(
            name="WatchlistGroup",
        ),
        migrations.DeleteModel(
            name="WatchlistItem",
        ),
    ]
