# Generated by Django 5.2.6 on 2025-12-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0007_alter_marketsession_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futuretrading24hour",
            name="country",
            field=models.CharField(
                choices=[
                    ("Canada", "Canada"),
                    ("China", "China"),
                    ("Futures", "Futures"),
                    ("Germany", "Germany"),
                    ("India", "India"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Pre_USA", "Pre_USA"),
                    ("USA", "USA"),
                    ("United Kingdom", "United Kingdom"),
                ],
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="futuretrading24hour",
            name="session_group",
            field=models.IntegerField(
                db_index=True, help_text="Shared key with MarketSession.capture_group"
            ),
        ),
    ]
