# Generated by Django 5.2.6 on 2025-10-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0007_alter_marketopensession_ym_entry_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="futuresnapshot",
            name="exit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price when target or stop was hit",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="futuresnapshot",
            name="exit_time",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when outcome was determined", null=True
            ),
        ),
        migrations.AddField(
            model_name="futuresnapshot",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("WORKED", "Worked"),
                    ("DIDNT_WORK", "Didn't Work"),
                    ("NEUTRAL", "Neutral"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                help_text="Trade outcome for this future",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="futuresnapshot",
            name="signal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUY", "Buy"),
                    ("STRONG_BUY", "Strong Buy"),
                    ("SELL", "Sell"),
                    ("STRONG_SELL", "Strong Sell"),
                    ("HOLD", "Hold"),
                ],
                help_text="TOTAL signal or individual future HBS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="futuresnapshot",
            name="weight",
            field=models.IntegerField(blank=True, help_text="Weight value", null=True),
        ),
    ]
