# Generated by Django 5.2.6 on 2025-10-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ThorTrading",
            "0008_futuresnapshot_exit_price_futuresnapshot_exit_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Rolling52WeekStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Trading symbol (YM, ES, NQ, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "high_52w",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Highest price in last 52 weeks",
                        max_digits=12,
                    ),
                ),
                (
                    "high_52w_date",
                    models.DateField(help_text="Date when 52w high was set"),
                ),
                (
                    "low_52w",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lowest price in last 52 weeks",
                        max_digits=12,
                    ),
                ),
                (
                    "low_52w_date",
                    models.DateField(help_text="Date when 52w low was set"),
                ),
                (
                    "last_price_checked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Most recent LAST price that was checked",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "all_time_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="All-time high (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "all_time_high_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when all-time high was set",
                        null=True,
                    ),
                ),
                (
                    "all_time_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="All-time low (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "all_time_low_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when all-time low was set",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "52-Week Stats",
                "verbose_name_plural": "52-Week Stats",
                "ordering": ["symbol"],
            },
        ),
    ]
