# Generated by Django 5.2.6 on 2025-12-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0008_alter_futuretrading24hour_country_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketsession",
            unique_together={("capture_group", "future")},
        ),
    ]
