1) “What symbols exist / metadata”

Instruments.Instrument is the canonical registry (symbol, asset_type, quote_source, name, exchange, currency, tick_size, point_value, is_active). 

instrument


If you have any other model elsewhere with symbol, asset_type, name, exchange, etc. (like legacy TradingInstrument), that is duplication and should eventually be deprecated.

✅ Goal: Instrument is the only place for symbol metadata.

2) “Which symbols should stream”

Right now you effectively have two representations:

UserInstrumentWatchlistItem (new, correct) — user chooses instrument, enabled/stream/order. 

watchlist

SchwabSubscription (older / streamer-facing) — user, symbol, asset_type, enabled. 

models

This is duplication, but it’s deliberate because:

Watchlist is your “UI + intent”

SchwabSubscription is your “stream bootstrap + cache”

You already have sync_watchlist_to_schwab() to keep them converged (eventually SchwabSubscription can be treated as derived).

✅ Goal: Watchlist is source-of-truth and SchwabSubscription becomes derived / internal.

3) “Which symbols a study uses”

StudyInstrument references Instrument and has enabled/order. 

study

This is not duplication of metadata — it’s a relationship (“study uses instrument”).

✅ This is correct.

What is NOT duplication (and is correct)

StudyInstrument.instrument -> Instrument is not copying symbol fields, it’s referencing them. 

study

Watchlist items referencing Instrument are also not copying metadata. 

watchlist

This is the right normalization.

Where duplication might be sneaking in (watch this)

In your enrich.py row builder you do:

"display_precision": getattr(inst, "display_precision", 2),
"tick_value": getattr(inst, "tick_value", None),
"margin_requirement": getattr(inst, "margin_requirement", None),
"sort_order": getattr(inst, "sort_order", idx),
"country": getattr(inst, "country", None),


But your current Instrument model does not define these fields (it has tick_size/point_value, not tick_value; no country/display_precision/margin_requirement/sort_order). 

instrument

So you’re not duplicating DB fields there — you’re doing “best effort” to support legacy objects. That’s okay short-term, but long-term you should decide:

Decide which fields belong in Instrument

If you truly need:

country

display_precision

margin_requirement

…then add them to Instrument and stop relying on legacy models.

Or, if those are “study-specific display fields”, they should live in:

StudyInstrument (per-study overrides), or

a separate InstrumentProfile / InstrumentMeta table.

Clean end-state (what you’re aiming for)

✅ One canonical symbol record

Instrument

✅ One canonical streaming intent

UserInstrumentWatchlistItem

Streamer reads from this (or a derived set)

✅ One canonical study universe

StudyInstrument

🧹 Optional cleanup later:

Treat SchwabSubscription as derived (or remove if streamer can read watchlist directly)

Remove legacy TradingInstrument once migration is complete# Generated by Django 5.2.6 on 2025-12-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0009_alter_marketsession_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradinginstrument",
            name="feed_symbol",
            field=models.CharField(
                blank=True,
                help_text="Raw feed symbol (/NQ, NQH26, etc.) when different from canonical code",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tradinginstrument",
            name="symbol",
            field=models.CharField(
                help_text="Canonical contract code (e.g., NQ, ES, AAPL)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
