# Generated by Django 5.2.6 on 2025-12-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0009_alter_marketsession_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradinginstrument",
            name="feed_symbol",
            field=models.CharField(
                blank=True,
                help_text="Raw feed symbol (/NQ, NQH26, etc.) when different from canonical code",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tradinginstrument",
            name="symbol",
            field=models.CharField(
                help_text="Canonical contract code (e.g., NQ, ES, AAPL)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
