# Generated by Django 5.2.6 on 2025-10-29 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0009_rolling52weekstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="FutureCloseSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        choices=[
                            ("YM", "Dow Jones (YM)"),
                            ("ES", "S&P 500 (ES)"),
                            ("NQ", "NASDAQ (NQ)"),
                            ("RTY", "Russell 2000 (RTY)"),
                            ("CL", "Crude Oil (CL)"),
                            ("SI", "Silver (SI)"),
                            ("HG", "Copper (HG)"),
                            ("GC", "Gold (GC)"),
                            ("VX", "Volatility (VX)"),
                            ("DX", "Dollar Index (DX)"),
                            ("ZB", "Bonds (ZB)"),
                            ("TOTAL", "TOTAL Composite"),
                        ],
                        help_text="Future symbol",
                        max_length=10,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bid_size", models.IntegerField(blank=True, null=True)),
                (
                    "ask",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ask_size", models.IntegerField(blank=True, null=True)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "vwap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "spread",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weighted_average",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BUY", "Buy"),
                            ("STRONG_BUY", "Strong Buy"),
                            ("SELL", "Sell"),
                            ("STRONG_SELL", "Strong Sell"),
                            ("HOLD", "Hold"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.IntegerField(blank=True, null=True)),
                (
                    "sum_weighted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "instrument_count",
                    models.IntegerField(blank=True, default=11, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Status (e.g., CLOSE TOTAL)",
                        max_length=20,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="futures_close",
                        to="ThorTrading.marketopensession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Future Close Snapshot",
                "verbose_name_plural": "Future Close Snapshots",
                "ordering": ["session", "symbol"],
                "unique_together": {("session", "symbol")},
            },
        ),
    ]

