# Generated by Django 5.2.6 on 2025-12-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0010_tradinginstrument_feed_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futuretrading24hour",
            name="country",
            field=models.CharField(
                choices=[
                    ("Canada", "Canada"),
                    ("China", "China"),
                    ("Germany", "Germany"),
                    ("India", "India"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Pre_USA", "Pre_USA"),
                    ("USA", "USA"),
                    ("United Kingdom", "United Kingdom"),
                ],
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country",
            field=models.CharField(
                choices=[
                    ("Canada", "Canada"),
                    ("China", "China"),
                    ("Germany", "Germany"),
                    ("India", "India"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Pre_USA", "Pre_USA"),
                    ("USA", "USA"),
                    ("United Kingdom", "United Kingdom"),
                ],
                help_text="Market region (canonical control market key)",
                max_length=50,
            ),
        ),
    ]
