# Generated by Django 5.2.6 on 2025-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0010_futureclosesnapshot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketopensession",
            old_name="ym_entry_price",
            new_name="entry_price",
        ),
        migrations.RenameField(
            model_name="marketopensession",
            old_name="ym_high_dynamic",
            new_name="target_high",
        ),
        migrations.RenameField(
            model_name="marketopensession",
            old_name="ym_low_dynamic",
            new_name="target_low",
        ),
        migrations.RemoveField(
            model_name="marketopensession",
            name="ym_ask",
        ),
        migrations.RemoveField(
            model_name="marketopensession",
            name="ym_bid",
        ),
        migrations.RemoveField(
            model_name="marketopensession",
            name="ym_close",
        ),
        migrations.RemoveField(
            model_name="marketopensession",
            name="ym_last",
        ),
        migrations.RemoveField(
            model_name="marketopensession",
            name="ym_open",
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="reference_ask",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reference ask price at capture",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="reference_bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reference bid price at capture",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="reference_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reference close price (e.g., YM previous close)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="reference_last",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reference last traded price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="reference_open",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reference open price (e.g., YM open)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
