# Generated by Django 5.2.6 on 2025-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ThorTrading",
            "0011_rename_ym_entry_price_marketopensession_entry_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="marketopensession",
            name="future",
            field=models.CharField(
                choices=[
                    ("YM", "Dow Jones (YM)"),
                    ("ES", "S&P 500 (ES)"),
                    ("NQ", "NASDAQ (NQ)"),
                    ("RTY", "Russell 2000 (RTY)"),
                    ("CL", "Crude Oil (CL)"),
                    ("SI", "Silver (SI)"),
                    ("HG", "Copper (HG)"),
                    ("GC", "Gold (GC)"),
                    ("VX", "Volatility (VX)"),
                    ("DX", "Dollar Index (DX)"),
                    ("ZB", "Bonds (ZB)"),
                    ("TOTAL", "TOTAL Composite"),
                ],
                default="YM",
                help_text="Primary future used for reference prices and trading",
                max_length=10,
            ),
        ),
    ]
