# Generated by Django 5.2.6 on 2025-12-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0011_alter_futuretrading24hour_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="capture_kind",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSE", "Close"), ("OTHER", "Other")],
                db_index=True,
                default="OPEN",
                help_text="Type of capture event (OPEN, CLOSE, OTHER)",
                max_length=20,
            ),
        ),
    ]
