# Generated by Django 5.2.6 on 2025-11-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0014_single_table_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketopensession",
            name="future",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOTAL", "TOTAL Composite"),
                    ("YM", "Dow Jones (YM)"),
                    ("ES", "S&P 500 (ES)"),
                    ("NQ", "NASDAQ (NQ)"),
                    ("RTY", "Russell 2000 (RTY)"),
                    ("CL", "Crude Oil (CL)"),
                    ("SI", "Silver (SI)"),
                    ("HG", "Copper (HG)"),
                    ("GC", "Gold (GC)"),
                    ("VX", "Volatility (VX)"),
                    ("DX", "Dollar Index (DX)"),
                    ("ZB", "Bonds (ZB)"),
                ],
                help_text="Future symbol for this capture row",
                max_length=10,
                null=True,
            ),
        ),
    ]
