# Generated by Django 5.2.6 on 2025-11-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0015_remove_future_default"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MarketOpenSession",
            new_name="MarketSession",
        ),
        migrations.AlterModelOptions(
            name="marketsession",
            options={
                "ordering": ["-captured_at", "future"],
                "verbose_name": "Market Session",
                "verbose_name_plural": "Market Sessions",
            },
        ),
    ]
