# Generated by Django 5.2.6 on 2025-12-24 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0016_add_country_to_tradinginstrument_and_vwapminute"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketTrading24Hour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_group",
                    models.IntegerField(
                        db_index=True,
                        help_text="Shared key with MarketSession.capture_group",
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Canada", "Canada"),
                            ("China", "China"),
                            ("Germany", "Germany"),
                            ("India", "India"),
                            ("Japan", "Japan"),
                            ("Mexico", "Mexico"),
                            ("Pre_USA", "Pre_USA"),
                            ("USA", "USA"),
                            ("United Kingdom", "United Kingdom"),
                        ],
                        help_text="Market region (canonical values only)",
                        max_length=32,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Instrument symbol (e.g., ES, YM, NQ, AAPL, SPY)",
                        max_length=32,
                    ),
                ),
                (
                    "prev_close_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_price_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_prev_diff_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_prev_pct_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "low_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "high_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "range_diff_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "range_pct_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "close_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cumulative volume across JP→US window",
                        null=True,
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False, help_text="True when US close is reached"
                    ),
                ),
            ],
            options={
                "verbose_name": "24-Hour Global Session",
                "verbose_name_plural": "24-Hour Global Sessions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="futuretrading24hour",
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name="contractweight",
            options={
                "ordering": ["instrument__country", "instrument__symbol"],
                "verbose_name": "Contract Weight",
                "verbose_name_plural": "Contract Weights",
            },
        ),
        migrations.AlterModelOptions(
            name="signalstatvalue",
            options={
                "ordering": ["instrument__country", "instrument__symbol", "signal"],
                "verbose_name": "Signal Statistical Value",
                "verbose_name_plural": "Signal Statistical Values",
            },
        ),
        migrations.AlterModelOptions(
            name="targethighlowconfig",
            options={
                "ordering": ["country", "symbol"],
                "verbose_name": "Target High/Low Config",
                "verbose_name_plural": "Target High/Low Configs",
            },
        ),
        migrations.AlterModelOptions(
            name="tradinginstrument",
            options={
                "ordering": ["sort_order", "country", "symbol"],
                "verbose_name": "Trading Instrument",
                "verbose_name_plural": "Trading Instruments",
            },
        ),
        migrations.AlterModelOptions(
            name="vwapminute",
            options={
                "ordering": ["-timestamp_minute", "country", "symbol"],
                "verbose_name": "VWAP Minute",
                "verbose_name_plural": "VWAP Minutes",
            },
        ),
        migrations.RemoveIndex(
            model_name="vwapminute",
            name="ThorTrading_symbol_e939f0_idx",
        ),
        migrations.RenameIndex(
            model_name="marketintraday",
            new_name="idx_intraday_twentyfour",
            old_name="ThorTrading_twentyf_37b3ab_idx",
        ),
        migrations.RunSQL(
            sql="UPDATE \"ThorTrading_marketintraday\" SET twentyfour_id = NULL;",
            reverse_sql="SELECT 1;",
        ),
        migrations.AlterUniqueTogether(
            name="marketintraday",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="buy_didnt_work",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="buy_didnt_work_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="buy_worked",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="buy_worked_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="high_52w",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="high_pct_52w",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="hold",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="low_52w",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="low_pct_52w",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="range_52w",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="range_pct_52w",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="sell_didnt_work",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="sell_didnt_work_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="sell_worked",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="sell_worked_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_buy_didnt_work",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_buy_didnt_work_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_buy_worked",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_buy_worked_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_sell_didnt_work",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_sell_didnt_work_percentage",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_sell_worked",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_sell_worked_percentage",
        ),
        migrations.AddField(
            model_name="marketsession",
            name="change",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="change_percent",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="vwap",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="ask_last",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="bid_last",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="close_1m",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="country",
            field=models.CharField(
                choices=[
                    ("Canada", "Canada"),
                    ("China", "China"),
                    ("Germany", "Germany"),
                    ("India", "India"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Pre_USA", "Pre_USA"),
                    ("USA", "USA"),
                    ("United Kingdom", "United Kingdom"),
                ],
                db_index=True,
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="high_1m",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="low_1m",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="open_1m",
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="spread_last",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="symbol",
            field=models.CharField(
                db_index=True, help_text="Instrument symbol", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="ask_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="ask_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="bhs",
            field=models.CharField(
                choices=[
                    ("BUY", "Buy"),
                    ("STRONG_BUY", "Strong Buy"),
                    ("SELL", "Sell"),
                    ("STRONG_SELL", "Strong Sell"),
                    ("HOLD", "Hold"),
                ],
                help_text="Signal from TOTAL or individual instrument",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="bid_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="bid_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="close_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country",
            field=models.CharField(
                choices=[
                    ("Canada", "Canada"),
                    ("China", "China"),
                    ("Germany", "Germany"),
                    ("India", "India"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Pre_USA", "Pre_USA"),
                    ("USA", "USA"),
                    ("United Kingdom", "United Kingdom"),
                ],
                help_text="Market region (canonical control market key)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country_symbol",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Numeric country/instrument metric kept next to symbol for ordering",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country_symbol_wndw_total",
            field=models.BigIntegerField(
                blank=True,
                help_text="Historical total count for this country/instrument window",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="entry_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="high_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="instrument_count",
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="last_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="low_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_close",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_close_vs_open_pct",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_high_open",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_high_pct_close",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_high_pct_open",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_low_open",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_low_pct_close",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_low_pct_open",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_open",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_range",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_range_pct",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="open_prev_diff_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="open_prev_pct_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="open_price_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="prev_close_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="range_diff_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="range_pct_24h",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="spread",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="symbol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOTAL", "TOTAL Composite"),
                    ("YM", "Dow Jones (YM)"),
                    ("ES", "S&P 500 (ES)"),
                    ("NQ", "NASDAQ (NQ)"),
                    ("RTY", "Russell 2000 (RTY)"),
                    ("CL", "Crude Oil (CL)"),
                    ("SI", "Silver (SI)"),
                    ("HG", "Copper (HG)"),
                    ("GC", "Gold (GC)"),
                    ("VX", "Volatility (VX)"),
                    ("DX", "Dollar Index (DX)"),
                    ("ZB", "Bonds (ZB)"),
                ],
                help_text="Instrument symbol for this capture row",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_high",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_hit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_hit_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_hit_type",
            field=models.CharField(
                blank=True,
                choices=[("TARGET", "Profit Target"), ("STOP", "Stop Loss")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_low",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="weighted_average",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="wndw",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WORKED", "Worked"),
                    ("DIDNT_WORK", "Didn't Work"),
                    ("NEUTRAL", "Neutral"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                help_text="Window/outcome label",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="all_time_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="All-time high (optional)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="all_time_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="All-time low (optional)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="high_52w",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Highest price in last 52 weeks",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="high_52w_date",
            field=models.DateField(help_text="Date when the 52-week high was set"),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="last_price_checked",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Most recent LAST price that was checked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="low_52w",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Lowest price in last 52 weeks",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="low_52w_date",
            field=models.DateField(help_text="Date when the 52-week low was set"),
        ),
        migrations.AlterField(
            model_name="rolling52weekstats",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Trading symbol (ES, YM, CL, AAPL, SPY, etc.)",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Deactivate without deleting. If inactive or disabled, targets are not computed.",
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="offset_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Absolute points above entry (BUY target / SELL stop)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="offset_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Absolute points below entry (BUY stop / SELL target)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="percent_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Percent above entry (e.g. 0.50 = +0.50%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="percent_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Percent below entry (e.g. 0.50 = -0.50%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Instrument symbol (YM, ES, NQ, RTY, CL, SI, HG, GC, VX, DX, ZB, AAPL, SPY, etc.)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="tradinginstrument",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="tradinginstrument",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Canonical instrument code (e.g., NQ, ES, AAPL)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vwapminute",
            name="last_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vwapminute",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Instrument symbol (YM, ES, NQ, AAPL, SPY, etc.)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="vwapminute",
            name="timestamp_minute",
            field=models.DateTimeField(db_index=True, help_text="UTC minute (floored)"),
        ),
        migrations.AlterUniqueTogether(
            name="targethighlowconfig",
            unique_together={("country", "symbol")},
        ),
        migrations.AddIndex(
            model_name="targethighlowconfig",
            index=models.Index(
                fields=["country", "symbol"], name="idx_thlc_country_symbol"
            ),
        ),
        migrations.AddIndex(
            model_name="targethighlowconfig",
            index=models.Index(
                fields=["country", "is_active"], name="idx_thlc_country_active"
            ),
        ),
        migrations.AddIndex(
            model_name="markettrading24hour",
            index=models.Index(
                fields=["session_date", "country", "symbol"],
                name="ThorTrading_session_8f105d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="markettrading24hour",
            unique_together={("session_group", "country", "symbol")},
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="twentyfour",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the associated 24h market record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intraday_bars",
                to="ThorTrading.markettrading24hour",
            ),
        ),
        migrations.AddIndex(
            model_name="marketintraday",
            index=models.Index(
                fields=["symbol", "country", "timestamp_minute"],
                name="idx_intraday_sym_cty_ts",
            ),
        ),
        migrations.AddIndex(
            model_name="marketintraday",
            index=models.Index(fields=["timestamp_minute"], name="idx_intraday_ts"),
        ),
        migrations.AddConstraint(
            model_name="marketintraday",
            constraint=models.UniqueConstraint(
                fields=("timestamp_minute", "symbol", "country"),
                name="uniq_intraday_minute_symbol_country",
            ),
        ),
        migrations.DeleteModel(
            name="FutureTrading24Hour",
        ),
    ]
