# Generated by Django 5.2.6 on 2025-12-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0017_markettrading24hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="buy_didnt_work",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="buy_didnt_work_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="buy_worked",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="buy_worked_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="high_52w",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="high_pct_52w",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="hold",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="low_52w",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="low_pct_52w",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="range_52w",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="range_pct_52w",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="sell_didnt_work",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="sell_didnt_work_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="sell_worked",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="sell_worked_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_buy_didnt_work",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_buy_didnt_work_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_buy_worked",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_buy_worked_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_sell_didnt_work",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_sell_didnt_work_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_sell_worked",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="strong_sell_worked_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=14, null=True
            ),
        ),
    ]
