# Generated by Django 5.2.6 on 2025-12-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0018_marketsession_buy_didnt_work_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsession",
            name="country_symbol",
            field=models.DecimalField(
                blank=True,
                db_column="country_instrument",
                decimal_places=4,
                help_text="Numeric country/instrument metric kept next to symbol for ordering",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country_symbol_wndw_total",
            field=models.BigIntegerField(
                blank=True,
                db_column="country_instrument_wndw_total",
                help_text="Historical total count for this country/instrument window",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="symbol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TOTAL", "TOTAL Composite"),
                    ("YM", "Dow Jones (YM)"),
                    ("ES", "S&P 500 (ES)"),
                    ("NQ", "NASDAQ (NQ)"),
                    ("RTY", "Russell 2000 (RTY)"),
                    ("CL", "Crude Oil (CL)"),
                    ("SI", "Silver (SI)"),
                    ("HG", "Copper (HG)"),
                    ("GC", "Gold (GC)"),
                    ("VX", "Volatility (VX)"),
                    ("DX", "Dollar Index (DX)"),
                    ("ZB", "Bonds (ZB)"),
                ],
                db_column="instrument",
                help_text="Instrument symbol for this capture row",
                max_length=32,
                null=True,
            ),
        ),
    ]
