# Generated by Django 5.2.6 on 2025-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0020_alter_marketsession_country_symbol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntradayInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_minute",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Minute bucket (UTC). Example: 2025-12-26 17:51:00+00:00",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                ("open_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("high_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("low_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("close_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("volume_1m", models.BigIntegerField(default=0)),
                (
                    "bid_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "ask_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "spread_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Intraday Instrument Bar",
                "verbose_name_plural": "Intraday Instrument Bars",
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp_minute"],
                        name="idx_intraday_instr_sym_ts",
                    ),
                    models.Index(
                        fields=["timestamp_minute"], name="idx_intraday_instr_ts"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("timestamp_minute", "symbol"),
                        name="uniq_intraday_symbol_minute",
                    )
                ],
            },
        ),
    ]
