# Generated by Django 5.2.6 on 2025-12-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0021_intradayinstrument"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IntradayInstrument",
            new_name="InstrumentIntraday",
        ),
        migrations.AlterModelOptions(
            name="instrumentintraday",
            options={
                "verbose_name": "Instrument Intraday Bar",
                "verbose_name_plural": "Instrument Intraday Bars",
            },
        ),
    ]
