# Generated by Django 5.2.6 on 2026-01-01 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0022_instrumentintraday_delete_intradayinstrument_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="marketsession",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="captured_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Exact timestamp of capture",
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_number",
            field=models.IntegerField(
                db_index=True,
                help_text="Trade counter/sequence number (groups all rows in the same market-open event)",
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="symbol",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Instrument symbol for this capture row (dynamic; admin/study-controlled)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="marketsession",
            constraint=models.UniqueConstraint(
                fields=("session_number", "symbol", "capture_kind", "country"),
                name="uniq_market_session_session_symbol_kind_country",
            ),
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="capture_group",
        ),
    ]
