# Generated by Django 5.2.6 on 2026-01-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0023_alter_marketsession_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketintraday",
            name="country",
            field=models.CharField(
                db_index=True,
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country",
            field=models.CharField(
                help_text="Market region (canonical control market key)", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="markettrading24hour",
            name="country",
            field=models.CharField(
                help_text="Market region (canonical values only)", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="markettrading24hour",
            name="session_group",
            field=models.IntegerField(
                db_index=True, help_text="Shared key with MarketSession.session_number"
            ),
        ),
        migrations.AlterField(
            model_name="targethighlowconfig",
            name="country",
            field=models.CharField(
                db_index=True,
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="tradinginstrument",
            name="country",
            field=models.CharField(
                db_index=True,
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="vwapminute",
            name="country",
            field=models.CharField(
                db_index=True,
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
    ]
