# Generated by Django 5.2.6 on 2025-11-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0024_marketsession_sell_didnt_work_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsession",
            old_name="strong_buy_didnt_worked_percentage",
            new_name="strong_buy_didnt_work_percentage",
        ),
    ]
