# Generated by Django 5.2.6 on 2026-01-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0025_study_studyinstrument"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MarketIntraday",
        ),
    ]
