# Generated by Django 5.2.6 on 2026-01-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0031_state_remove_rtd_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studyinstrument",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studyinstrument",
            name="study",
        ),
        migrations.RemoveField(
            model_name="studyinstrument",
            name="instrument",
        ),
        migrations.DeleteModel(
            name="Study",
        ),
        migrations.DeleteModel(
            name="StudyInstrument",
        ),
    ]
