# Generated by hand to move session_bid + bid_size adjacent to wndw
from django.db import migrations


FORWARD_SQL = r"""
DO $$
DECLARE
    tbl CONSTANT text := 'FutureTrading_marketsession';
    tmp CONSTANT text := 'FutureTrading_marketsession_tmp';
    col_list text;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = tbl
    ) THEN
        RAISE EXCEPTION 'Table % does not exist; abort reorder', tbl;
    END IF;

    EXECUTE format('DROP TABLE IF EXISTS %I CASCADE', tmp);

    EXECUTE '
        CREATE TABLE "FutureTrading_marketsession_tmp" (
            id SERIAL PRIMARY KEY,
            session_number integer NOT NULL,
            year integer NOT NULL,
            month integer NOT NULL,
            date integer NOT NULL,
            day varchar(10) NOT NULL,
            captured_at timestamp with time zone NOT NULL,
            country varchar(50) NOT NULL,
            future varchar(10),
            country_future numeric(10,2),
            weight integer,
            bhs varchar(20) NOT NULL,
            wndw varchar(20) NOT NULL,
            session_bid numeric(10,2),
            bid_size integer,
            last_price numeric(10,2),
            session_ask numeric(10,2),
            ask_size integer,
            country_future_wndw_total numeric(10,2),
            strong_buy_worked numeric(10,2),
            strong_buy_worked_percentage numeric(10,4),
            strong_buy_didnt_work numeric(10,2),
            strong_buy_didnt_work_percentage numeric(10,4),
            buy_worked numeric(10,2),
            buy_worked_percentage numeric(10,4),
            buy_didnt_work numeric(10,2),
            buy_didnt_work_percentage numeric(10,4),
            hold numeric(10,2),
            hold_percentage numeric(10,4),
            strong_sell_worked numeric(10,2),
            strong_sell_worked_percentage numeric(10,4),
            strong_sell_didnt_work numeric(10,2),
            strong_sell_didnt_work_percentage numeric(10,4),
            sell_worked numeric(10,2),
            sell_worked_percentage numeric(10,4),
            sell_didnt_work numeric(10,2),
            sell_didnt_work_percentage numeric(10,4),
            session_close numeric(10,2),
            session_open numeric(10,2),
            open_vs_prev_number numeric(10,2),
            open_vs_prev_percent numeric(10,4),
            volume bigint,
            vwap numeric(10,2),
            spread numeric(10,2),
            entry_price numeric(10,2),
            target_high numeric(10,2),
            target_low numeric(10,2),
            weighted_average numeric(10,4),
            instrument_count integer,
            strong_sell_flag boolean NOT NULL,
            study_fw varchar(50) NOT NULL,
            fw_weight numeric(10,4),
            outcome varchar(20) NOT NULL,
            didnt_work boolean NOT NULL,
            fw_nwdw varchar(20) NOT NULL,
            exit_price numeric(10,2),
            exit_time timestamp with time zone,
            fw_exit_value numeric(10,2),
            fw_exit_percent numeric(10,4),
            fw_stopped_out_value numeric(10,2),
            fw_stopped_out_nwdw varchar(20) NOT NULL,
            close_last_price numeric(10,2),
            close_change numeric(10,2),
            close_change_percent numeric(10,4),
            close_bid numeric(10,2),
            close_bid_size integer,
            close_ask numeric(10,2),
            close_ask_size integer,
            close_volume bigint,
            close_vwap numeric(10,2),
            close_spread numeric(10,2),
            close_captured_at timestamp with time zone,
            close_weighted_average numeric(10,4),
            close_signal varchar(20) NOT NULL,
            close_weight integer,
            close_sum_weighted numeric(10,2),
            close_instrument_count integer,
            close_status varchar(50) NOT NULL,
            created_at timestamp with time zone NOT NULL,
            updated_at timestamp with time zone NOT NULL,
            day_24h_high numeric(10,2),
            day_24h_low numeric(10,2),
            range_high_low numeric(10,2),
            range_percent numeric(10,4),
            week_52_high numeric(10,2),
            week_52_low numeric(10,2),
            week_52_range_high_low numeric(10,2),
            week_52_range_percent numeric(10,4),
            change numeric(10,2),
            change_percent numeric(10,4),
            CONSTRAINT ft_msession_tmp_cymdf_key_36 UNIQUE (country, year, month, date, future)
        );
    ';

    col_list := 'id, session_number, year, month, date, day, captured_at, country, future, country_future, weight, '
        || 'bhs, wndw, session_bid, bid_size, last_price, session_ask, ask_size, '
        || 'country_future_wndw_total, strong_buy_worked, strong_buy_worked_percentage, strong_buy_didnt_work, '
        || 'strong_buy_didnt_work_percentage, buy_worked, buy_worked_percentage, buy_didnt_work, buy_didnt_work_percentage, '
        || 'hold, hold_percentage, strong_sell_worked, strong_sell_worked_percentage, strong_sell_didnt_work, '
        || 'strong_sell_didnt_work_percentage, sell_worked, sell_worked_percentage, sell_didnt_work, sell_didnt_work_percentage, '
        || 'session_close, session_open, open_vs_prev_number, open_vs_prev_percent, '
        || 'volume, vwap, spread, entry_price, target_high, target_low, weighted_average, instrument_count, '
        || 'strong_sell_flag, study_fw, fw_weight, outcome, didnt_work, fw_nwdw, exit_price, exit_time, '
        || 'fw_exit_value, fw_exit_percent, fw_stopped_out_value, fw_stopped_out_nwdw, '
        || 'close_last_price, close_change, close_change_percent, close_bid, close_bid_size, close_ask, close_ask_size, '
        || 'close_volume, close_vwap, close_spread, close_captured_at, close_weighted_average, close_signal, close_weight, '
        || 'close_sum_weighted, close_instrument_count, close_status, created_at, updated_at, '
        || 'day_24h_high, day_24h_low, range_high_low, range_percent, week_52_high, week_52_low, week_52_range_high_low, '
        || 'week_52_range_percent, change, change_percent';

    EXECUTE format(
        'INSERT INTO %I (%s) SELECT %s FROM %I',
        tmp,
        col_list,
        col_list,
        tbl
    );

    EXECUTE format('DROP TABLE %I', tbl);
    EXECUTE format('ALTER TABLE %I RENAME TO %I', tmp, tbl);

    PERFORM setval(
        pg_get_serial_sequence('"FutureTrading_marketsession"','id'),
        GREATEST(1, COALESCE((SELECT MAX(id) FROM "FutureTrading_marketsession"), 0))
    );
END$$;
"""

REVERSE_SQL = "SELECT 1;"


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0035_reorder_session_ask_after_last_price"),
    ]

    operations = [
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
