# Generated by Django 5.2.6 on 2025-11-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0036_reorder_session_bid_after_wndw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketsession",
            name="close_ask",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_ask_size",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_bid",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_bid_size",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_captured_at",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_change",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_change_percent",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_instrument_count",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_last_price",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_signal",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_spread",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_status",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_sum_weighted",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_volume",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_vwap",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_weight",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="close_weighted_average",
        ),
    ]
