# Generated by Django 5.2.6 on 2025-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0039_move_entry_fields_after_ask_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetHighLowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Trading symbol (YM, ES, NQ, RTY, CL, SI, HG, GC, VX, DX, ZB)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("POINTS", "Points"),
                            ("PERCENT", "Percent"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="POINTS",
                        help_text="Computation mode: Points adds/subtracts fixed amounts; Percent uses percentage offsets; Disabled skips target calculation.",
                        max_length=10,
                    ),
                ),
                (
                    "offset_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute points above entry (BUY target / SELL stop)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "offset_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Absolute points below entry (BUY stop / SELL target)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "percent_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent above entry (e.g. 0.50 = +0.50%)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "percent_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percent below entry (e.g. 0.50 = -0.50%)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate without deleting. If inactive or disabled, capture falls back to legacy default if no other config exists.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Target High/Low Config",
                "verbose_name_plural": "Target High/Low Configs",
                "ordering": ["symbol"],
            },
        ),
    ]
