# Generated by Django 5.2.6 on 2025-11-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0041_remove_marketsession_didnt_work_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketsession",
            name="strong_sell_flag",
        ),
    ]
