# Generated by Django 5.2.6 on 2025-11-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0042_remove_marketsession_strong_sell_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsession",
            name="buy_didnt_work",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Buy signals that did not work",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="buy_didnt_work_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of buys that failed",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="buy_worked",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Buy signals that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="buy_worked_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of buys that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="change",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Price change from previous close",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="change_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Percentage change",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country_future",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Numeric country future metric kept next to future for ordering",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="country_future_wndw_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Country-level total for wndw aggregation",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="day_24h_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="24 hour high",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="day_24h_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="24 hour low",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="entry_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Actual entry (Ask if buying, Bid if selling)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="hold",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Hold signals count",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="hold_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of holds",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="last_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Last traded price at market open",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="open_vs_prev_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Open vs Prev (Number)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="open_vs_prev_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Open vs Prev (%)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="range_high_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Range (24h High - 24h Low)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="range_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Range as % of previous close",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="sell_didnt_work",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Sell signals that failed",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="sell_didnt_work_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of sells that failed",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="sell_worked",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Sell signals that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="sell_worked_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of sells that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_ask",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Ask price at capture",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Bid price at capture (renamed from reference_bid)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Previous close price",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_open",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Open price",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="spread",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Bid-Ask spread",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_buy_didnt_work",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Strong buy signals that did not work",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_buy_didnt_work_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of strong buys that failed",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_buy_worked",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Strong buy signals that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_buy_worked_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of strong buys that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_sell_didnt_work",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Strong sell signals that failed",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_sell_didnt_work_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of strong sells that failed",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_sell_worked",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Strong sell signals that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="strong_sell_worked_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent of strong sells that worked",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Configurable target above entry (per TargetHighLowConfig)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Configurable stop below entry (per TargetHighLowConfig)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="vwap",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Volume Weighted Average Price",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="week_52_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="52-week high",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="week_52_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="52-week low",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="week_52_range_high_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="52-week range (High - Low)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="week_52_range_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="52-week range as % of current price",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="weighted_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="TOTAL weighted average (e.g., -0.109)",
                max_digits=14,
                null=True,
            ),
        ),
    ]
