# Generated by Django 5.2.6 on 2025-11-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0050_rename_session_bid_session_ask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsession",
            name="bid_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Bid price at capture",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="wndw",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WORKED", "Worked"),
                    ("DIDNT_WORK", "Didn't Work"),
                    ("NEUTRAL", "Neutral"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                help_text="Window/outcome label (Worked / Didn't Work / Neutral / Pending)",
                max_length=20,
                null=True,
            ),
        ),
    ]
