# Generated by Django 5.2.6 on 2025-11-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0056_reorder_market_profile_metrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketsession",
            name="market_close_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Close move from open (number)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_close_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Close move from open (percent)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_high_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="High move from open (number)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_high_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="High move from open (percent)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_low_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Low move from open (number)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_low_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Low move from open (percent)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_open",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Market open move (number)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_range_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Intraday range (number)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="market_range_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Intraday range (percent)",
                max_digits=14,
                null=True,
            ),
        ),
    ]
