# Generated by Django 5.2.6 on 2025-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0057_alter_marketsession_market_close_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="target_hit_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the first target or stop was hit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="target_hit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Price at which the first target or stop was hit",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="target_hit_type",
            field=models.CharField(
                blank=True,
                choices=[("TARGET", "Profit Target"), ("STOP", "Stop Loss")],
                help_text="Which level was hit first: profit TARGET or STOP",
                max_length=10,
                null=True,
            ),
        ),
    ]
