# Generated by Django 5.2.6 on 2025-11-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0058_marketsession_target_hit_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="capture_group",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Group identifier for all rows captured in the same market-open event",
                null=True,
            ),
        ),
    ]
