# Generated by Django 5.2.6 on 2025-11-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0059_marketsession_capture_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="VwapMinute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "timestamp_minute",
                    models.DateTimeField(help_text="UTC minute (floored)"),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "bid_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ask_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "cumulative_volume",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Cumulative volume from feed at sample time",
                        null=True,
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp_minute", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp_minute"],
                        name="FutureTradi_symbol_97ecec_idx",
                    )
                ],
                "unique_together": {("symbol", "timestamp_minute")},
            },
        ),
    ]
