# Generated by Django 5.2.6 on 2025-11-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0060_vwapminute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vwapminute",
            name="ask_price",
        ),
        migrations.RemoveField(
            model_name="vwapminute",
            name="bid_price",
        ),
    ]
