# Generated by Django 5.2.6 on 2025-11-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0065_country_future_wndw_total_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketsession",
            name="hold_percentage",
        ),
    ]
