# Generated by Django 5.2.6 on 2025-11-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0067_marketsession_rename_24h_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsession",
            old_name="day_24h_high",
            new_name="high_24h",
        ),
        migrations.RenameField(
            model_name="marketsession",
            old_name="day_24h_low",
            new_name="low_24h",
        ),
    ]
