# Generated by Django 5.2.6 on 2025-11-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0068_rename_day_24h_high_marketsession_high_24h_and_more"),
    ]

    operations = [
        # Intentionally left blank.
        # Renames handled in 0069_rename_marketsession_range_fields to avoid conflicts.
    ]
