# Generated by Django 5.2.6 on 2025-11-27 01:42

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations
from django.db.utils import OperationalError, ProgrammingError


class SafeRenameField(migrations.RenameField):
    """RenameField that silently skips when the source column was already renamed."""

    def state_forwards(self, app_label, state):
        try:
            super().state_forwards(app_label, state)
        except FieldDoesNotExist:
            return

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except (FieldDoesNotExist, ProgrammingError, OperationalError):
            return

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_backwards(app_label, schema_editor, from_state, to_state)
        except (FieldDoesNotExist, ProgrammingError, OperationalError):
            return


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0068_rename_day_24h_high_marketsession_high_24h_and_more"),
    ]

    operations = [
        SafeRenameField(
            model_name="marketsession",
            old_name="range_high_low",
            new_name="range_diff_24h",
        ),
        SafeRenameField(
            model_name="marketsession",
            old_name="range_percent",
            new_name="range_pct_24h",
        ),
    ]
