# Generated by Django 5.2.6 on 2025-11-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0069_remove_marketsession_range_high_low_and_more"),
        ("ThorTrading", "0069_rename_marketsession_range_fields"),
    ]

    operations = []
