# Generated by Django 5.2.6 on 2025-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0071_marketsession_low_pct_52"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="marketsession",
                    name="status",
                ),
                migrations.RemoveField(
                    model_name="marketsession",
                    name="sum_weighted",
                ),
                migrations.AlterField(
                    model_name="marketsession",
                    name="open_prev_diff_24h",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h Open − Prev 24h Close (number)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="marketsession",
                    name="open_prev_pct_24h",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h Open − Prev 24h Close (%)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="marketsession",
                    name="open_price_24h",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Current 24h open price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="marketsession",
                    name="prev_close_24h",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Previous 24h close price",
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="marketsession",
                    name="range_diff_24h",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h range difference (High - Low)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name="marketsession",
                    name="range_pct_24h",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="24h range as % of previous close",
                        max_digits=14,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
