# Generated by Django 5.2.6 on 2025-11-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0073_marketsession_high_pct_52"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsession",
            old_name="week_52_high",
            new_name="high_52w",
        ),
        migrations.RenameField(
            model_name="marketsession",
            old_name="week_52_low",
            new_name="low_52w",
        ),
        migrations.RenameField(
            model_name="marketsession",
            old_name="low_pct_52",
            new_name="low_pct_52w",
        ),
    ]
