# Generated by Django 5.2.6 on 2025-11-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0074_rename_week_52_high_marketsession_high_52w_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsession",
            old_name="week_52_range_high_low",
            new_name="range_52w",
        ),
        migrations.RenameField(
            model_name="marketsession",
            old_name="week_52_range_percent",
            new_name="range_pct_52w",
        ),
    ]
