# Generated by Django 5.2.6 on 2025-11-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0080_marketsession_close_vs_open_pct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsession",
            old_name="market_high_drawdown_pct",
            new_name="market_high_pct_open",
        ),
    ]
