# Generated by Django 5.2.6 on 2025-11-30 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0082_remove_marketsession_vwap"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="close_24h",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Global 24h close for this session (set at US close)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FutureTrading24Hour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_group",
                    models.CharField(
                        db_index=True,
                        help_text="Shared key with MarketSession.capture_group",
                        max_length=32,
                    ),
                ),
                ("session_date", models.DateField(db_index=True)),
                ("country", models.CharField(max_length=10)),
                ("future", models.CharField(max_length=10)),
                (
                    "prev_close_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_price_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_prev_diff_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "open_prev_pct_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "low_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "high_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "range_diff_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "range_pct_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "close_24h",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "finalized",
                    models.BooleanField(
                        default=False, help_text="True when US close is reached"
                    ),
                ),
            ],
            options={
                "verbose_name": "24-Hour Global Session",
                "verbose_name_plural": "24-Hour Global Sessions",
                "indexes": [
                    models.Index(
                        fields=["session_date", "country", "future"],
                        name="FutureTradi_session_c04980_idx",
                    )
                ],
                "unique_together": {("session_group", "future")},
            },
        ),
        migrations.CreateModel(
            name="MarketIntraday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_minute",
                    models.DateTimeField(
                        db_index=True, help_text="Minute bucket (UTC)"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Market region (e.g., USA, JPN, LON)", max_length=10
                    ),
                ),
                (
                    "future",
                    models.CharField(
                        help_text="Future symbol (e.g., ES, YM, NQ)", max_length=10
                    ),
                ),
                (
                    "market_code",
                    models.CharField(
                        help_text="Market code (e.g., USA, JPN, LON)", max_length=10
                    ),
                ),
                ("open_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("high_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("low_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("close_1m", models.DecimalField(decimal_places=4, max_digits=14)),
                ("volume_1m", models.BigIntegerField()),
                (
                    "bid_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "ask_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "spread_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "twentyfour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intraday_bars",
                        to="ThorTrading.futuretrading24hour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Intraday Bar",
                "verbose_name_plural": "Market Intraday Bars",
                "indexes": [
                    models.Index(
                        fields=["twentyfour"], name="FutureTradi_twentyf_b1f6e6_idx"
                    )
                ],
                "unique_together": {("timestamp_minute", "future", "country")},
            },
        ),
    ]

