# Generated by Django 5.2.6 on 2025-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0083_marketsession_close_24h_futuretrading24hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="futuretrading24hour",
            name="volume_24h",
            field=models.BigIntegerField(
                blank=True, help_text="Cumulative volume across JP→US window", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="session_volume",
            field=models.BigIntegerField(
                blank=True,
                help_text="Cumulative volume while this market is OPEN",
                null=True,
            ),
        ),
    ]
