# Generated by Django 5.2.6 on 2025-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0084_futuretrading24hour_volume_24h_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradinginstrument",
            name="show_in_ribbon",
            field=models.BooleanField(default=False),
        ),
    ]
