# Generated by Django 5.2.6 on 2025-12-03 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0085_tradinginstrument_show_in_ribbon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractweight",
            name="instrument",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_weight",
                to="ThorTrading.tradinginstrument",
            ),
        ),
        migrations.AlterField(
            model_name="futuretrading24hour",
            name="country",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="futuretrading24hour",
            name="future",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="marketintraday",
            name="twentyfour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intraday_bars",
                to="ThorTrading.futuretrading24hour",
            ),
        ),
        migrations.AlterField(
            model_name="signalstatvalue",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signal_stat_values",
                to="ThorTrading.tradinginstrument",
            ),
        ),
        migrations.AlterField(
            model_name="tradinginstrument",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruments",
                to="ThorTrading.instrumentcategory",
            ),
        ),
    ]
