# Generated by Django 5.2.6 on 2025-12-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThorTrading", "0086_alter_contractweight_instrument_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="futuretrading24hour",
            new_name="ThorTrading_session_6fb660_idx",
            old_name="FutureTradi_session_c04980_idx",
        ),
        migrations.RenameIndex(
            model_name="marketintraday",
            new_name="ThorTrading_twentyf_37b3ab_idx",
            old_name="FutureTradi_twentyf_b1f6e6_idx",
        ),
        migrations.RenameIndex(
            model_name="vwapminute",
            new_name="ThorTrading_symbol_e939f0_idx",
            old_name="FutureTradi_symbol_97ecec_idx",
        ),
    ]
