# Generated by Django 5.2.6 on 2026-01-08 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier used by API/WS. Example: 'new_york', 'london', 'tokyo'.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "timezone_name",
                    models.CharField(
                        help_text="IANA timezone. Example: 'America/New_York', 'Europe/London'.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLOSED", "Closed"),
                            ("PREMARKET", "Premarket"),
                            ("OPEN", "Open"),
                        ],
                        default="CLOSED",
                        max_length=12,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="GlobalMarke_is_acti_9d5339_idx",
                    ),
                    models.Index(
                        fields=["status"], name="GlobalMarke_status_4fbf13_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("is_closed", models.BooleanField(default=True)),
                ("early_close_time", models.TimeField(blank=True, null=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="GlobalMarkets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["market_id", "-date"],
                "indexes": [
                    models.Index(
                        fields=["market", "date"], name="GlobalMarke_market__0ae448_idx"
                    ),
                    models.Index(fields=["date"], name="GlobalMarke_date_93d1d6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "date"), name="uniq_market_holiday_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(help_text="0=Mon ... 6=Sun"),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the market is always closed on this weekday.",
                    ),
                ),
                ("premarket_open_time", models.TimeField(blank=True, null=True)),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="GlobalMarkets.market",
                    ),
                ),
            ],
            options={
                "ordering": ["market_id", "weekday"],
                "indexes": [
                    models.Index(
                        fields=["market", "weekday"],
                        name="GlobalMarke_market__eea884_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("market", "weekday"), name="uniq_market_session_weekday"
                    )
                ],
            },
        ),
    ]
