# Generated by Django 5.2.6 on 2025-10-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="is_control_market",
            field=models.BooleanField(
                default=False, help_text="Is this one of the 9 global control markets?"
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Weight in global composite index (0.00 - 1.00)",
                max_digits=4,
            ),
        ),
        migrations.CreateModel(
            name="GlobalMarketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "global_composite_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weighted global influence score (0-100)",
                        max_digits=6,
                    ),
                ),
                (
                    "active_markets_count",
                    models.IntegerField(
                        default=0, help_text="How many control markets are OPEN"
                    ),
                ),
                (
                    "session_phase",
                    models.CharField(
                        choices=[
                            ("ASIAN", "Asian Session"),
                            ("EUROPEAN", "European Session"),
                            ("AMERICAN", "American Session"),
                            ("OVERLAP", "Overlap/After-hours"),
                        ],
                        help_text="Current dominant trading session",
                        max_length=20,
                    ),
                ),
                ("contributions_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Global Market Index",
                "verbose_name_plural": "Global Market Indices",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="GlobalMarke_timesta_fdd160_idx"
                    ),
                    models.Index(
                        fields=["session_phase"], name="GlobalMarke_session_687be3_idx"
                    ),
                ],
            },
        ),
    ]
