# Generated by Django 5.2.6 on 2025-10-28 18:00

from django.db import migrations
from decimal import Decimal


def set_control_markets(apps, schema_editor):
    """Set the 9 control markets with their weights"""
    Market = apps.get_model('GlobalMarkets', 'Market')
    
    CONTROL_MARKETS = {
        'Japan': Decimal('0.25'),
        'China': Decimal('0.10'),
        'India': Decimal('0.05'),
        'Germany': Decimal('0.20'),
        'United Kingdom': Decimal('0.05'),
        'Pre_USA': Decimal('0.05'),
        'USA': Decimal('0.25'),
        'Canada': Decimal('0.03'),
        'Mexico': Decimal('0.02'),
    }
    
    # First, unmark all markets
    Market.objects.all().update(is_control_market=False, weight=Decimal('0.00'))
    
    # Then mark the 9 control markets
    for country, weight in CONTROL_MARKETS.items():
        Market.objects.filter(country=country).update(
            is_control_market=True,
            weight=weight
        )


def reverse_control_markets(apps, schema_editor):
    """Reverse: unmark all control markets"""
    Market = apps.get_model('GlobalMarkets', 'Market')
    Market.objects.all().update(is_control_market=False, weight=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0002_market_is_control_market_market_weight_and_more"),
    ]

    operations = [
        migrations.RunPython(set_control_markets, reverse_control_markets),
    ]
