# Generated by Django 5.2.6 on 2025-11-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0003_set_control_markets"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="enable_close_capture",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, skip futures CLOSE capture for this market.",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="enable_futures_capture",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, this market will NOT create FutureTrading MarketSession rows. Use for redundant markets (e.g., Canada/Mexico) that mirror USA data.",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="enable_open_capture",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, skip futures OPEN capture for this market.",
            ),
        ),
    ]
