# Generated by Django 5.2.6 on 2026-01-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0003_remove_market_sessions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=12)),
                ("new_status", models.CharField(max_length=12)),
                ("changed_at", models.DateTimeField(db_index=True)),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                ("next_transition_utc", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "GlobalMarkets_marketholiday" DROP CONSTRAINT IF EXISTS "uniq_market_holiday_date";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="marketholiday",
                    name="uniq_market_holiday_date",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER TABLE "GlobalMarkets_marketholiday" DROP CONSTRAINT IF EXISTS "uniq_holiday_date";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="marketholiday",
                    name="uniq_holiday_date",
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'DROP INDEX IF EXISTS "GlobalMarke_market__0ae448_idx";',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="marketholiday",
                    name="GlobalMarke_market__0ae448_idx",
                )
            ],
        ),
        migrations.AlterField(
            model_name="market",
            name="close_time",
            field=models.TimeField(
                blank=True,
                help_text="Default market close time (local timezone). Example: 16:00",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="open_time",
            field=models.TimeField(
                blank=True,
                help_text="Default market open time (local timezone). Example: 09:00",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketholiday",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="marketholiday",
            name="early_close_time",
            field=models.TimeField(
                blank=True,
                help_text="If set, markets close early at this time (ET)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketholiday",
            name="is_closed",
            field=models.BooleanField(default=True, help_text="Full day closure"),
        ),
        migrations.AlterField(
            model_name="marketholiday",
            name="name",
            field=models.CharField(
                help_text="Holiday name (e.g., 'Thanksgiving', 'Christmas')",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="marketstatusevent",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="GlobalMarkets.market",
            ),
        ),
        migrations.AddIndex(
            model_name="marketstatusevent",
            index=models.Index(
                fields=["market", "-changed_at"], name="GlobalMarke_market__ffd398_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketstatusevent",
            index=models.Index(
                fields=["new_status", "-changed_at"],
                name="GlobalMarke_new_sta_02ae07_idx",
            ),
        ),
    ]
