# Generated by Django 5.2.6 on 2025-11-21 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0004_market_enable_close_capture_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalmarketindex",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="marketholiday",
            options={
                "ordering": ["market__country", "-date"],
                "verbose_name": "Market Holiday",
                "verbose_name_plural": "Market Holidays",
            },
        ),
        migrations.RemoveIndex(
            model_name="globalmarketindex",
            name="GlobalMarke_timesta_fdd160_idx",
        ),
        migrations.RemoveIndex(
            model_name="globalmarketindex",
            name="GlobalMarke_session_687be3_idx",
        ),
        migrations.RemoveField(
            model_name="globalmarketindex",
            name="active_markets_count",
        ),
        migrations.RemoveField(
            model_name="globalmarketindex",
            name="contributions_json",
        ),
        migrations.RemoveField(
            model_name="globalmarketindex",
            name="session_phase",
        ),
        migrations.RemoveField(
            model_name="marketholiday",
            name="name",
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="americas_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Composite score for American markets",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="asia_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Composite score for Asian markets",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="europe_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Composite score for European markets",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="markets_bearish",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="markets_bullish",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="markets_neutral",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="globalmarketindex",
            name="markets_open",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marketholiday",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketholiday",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="marketholiday",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="globalmarketindex",
            name="global_composite_score",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Overall global sentiment score (-100 to +100)",
                max_digits=6,
            ),
        ),
    ]
