# Generated by Django 5.2.6 on 2026-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0004_marketstatusevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Display label for the Country column (admin-controlled). Example: 'Japan', 'United Kingdom'.",
                max_length=80,
            ),
        ),
    ]
