# Generated by Django 5.2.6 on 2025-12-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0005_alter_globalmarketindex_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="country",
            field=models.CharField(
                choices=[
                    ("Canada", "Canada"),
                    ("China", "China"),
                    ("Germany", "Germany"),
                    ("India", "India"),
                    ("Japan", "Japan"),
                    ("Mexico", "Mexico"),
                    ("Pre_USA", "Pre_USA"),
                    ("USA", "USA"),
                    ("United Kingdom", "United Kingdom"),
                ],
                max_length=50,
            ),
        ),
    ]
