# Generated by Django 5.2.6 on 2025-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0006_alter_market_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalmarketindex",
            name="americas_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="globalmarketindex",
            name="asia_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="globalmarketindex",
            name="europe_score",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="globalmarketindex",
            name="global_composite_score",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name="market",
            name="enable_close_capture",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="market",
            name="enable_futures_capture",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="market",
            name="enable_open_capture",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="market",
            name="is_control_market",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="market",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
