# Generated by Django 5.2.6 on 2025-12-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0008_alter_market_timezone_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="country",
            field=models.CharField(max_length=50),
        ),
    ]
