# Generated by Django 5.2.6 on 2025-12-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0009_alter_market_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="market",
            name="is_control_market",
        ),
        migrations.RemoveField(
            model_name="market",
            name="weight",
        ),
    ]
