# Generated by Django 5.2.6 on 2025-12-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0013_remove_market_enable_futures_capture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usmarketstatus",
            options={
                "ordering": ["-date"],
                "verbose_name": "Trading Calendar",
                "verbose_name_plural": "Trading Calendars",
            },
        ),
        migrations.AlterModelTable(
            name="usmarketstatus",
            table="GlobalMarkets_usmarketstatus",
        ),
    ]
