# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalMarkets', '0016_remove_futures_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Admin-controlled display order (lower first)'),
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['sort_order', 'country'], 'verbose_name': 'Market', 'verbose_name_plural': 'Markets'},
        ),
    ]
