# Generated by Django 5.2.6 on 2026-01-08 21:33

import uuid
import django.db.models.deletion
from django.db import migrations, models


def _populate_market_keys(apps, schema_editor):
    Market = apps.get_model("GlobalMarkets", "Market")
    for obj in Market.objects.all().only("id", "key"):
        obj.key = f"mkt_{obj.id}"
        obj.save(update_fields=["key"])


class Migration(migrations.Migration):

    dependencies = [
        ("GlobalMarkets", "0017_market_sort_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(help_text="0=Mon ... 6=Sun"),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="If true, the market is always closed on this weekday.",
                    ),
                ),
                ("premarket_open_time", models.TimeField(blank=True, null=True)),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["market_id", "weekday"],
            },
        ),
        migrations.DeleteModel(
            name="GlobalMarketIndex",
        ),
        migrations.RemoveField(
            model_name="marketdatasnapshot",
            name="market",
        ),
        migrations.AlterUniqueTogether(
            name="usermarketwatchlist",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usermarketwatchlist",
            name="market",
        ),
        migrations.RemoveField(
            model_name="usermarketwatchlist",
            name="user",
        ),
        migrations.DeleteModel(
            name="USMarketStatus",
        ),
        migrations.AlterModelOptions(
            name="market",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="marketholiday",
            options={"ordering": ["market_id", "-date"]},
        ),
        migrations.RenameField(
            model_name="marketholiday",
            old_name="full_day",
            new_name="is_closed",
        ),
        migrations.AlterUniqueTogether(
            name="marketholiday",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="market",
            name="country",
        ),
        migrations.RemoveField(
            model_name="market",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="market",
            name="enable_close_capture",
        ),
        migrations.RemoveField(
            model_name="market",
            name="enable_open_capture",
        ),
        migrations.RemoveField(
            model_name="market",
            name="enable_session_capture",
        ),
        migrations.RemoveField(
            model_name="market",
            name="market_close_time",
        ),
        migrations.RemoveField(
            model_name="market",
            name="market_open_time",
        ),
        migrations.RemoveField(
            model_name="market",
            name="trading_days",
        ),
        migrations.AddField(
            model_name="market",
            name="key",
            field=models.SlugField(
                default=uuid.uuid4,
                help_text="Stable identifier used by API/WS. Example: 'new_york', 'london', 'tokyo'.",
                max_length=40,
                unique=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="name",
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketholiday",
            name="early_close_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketholiday",
            name="name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="market",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="market",
            name="status",
            field=models.CharField(
                choices=[
                    ("CLOSED", "Closed"),
                    ("PREMARKET", "Premarket"),
                    ("OPEN", "Open"),
                ],
                default="CLOSED",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="market",
            name="timezone_name",
            field=models.CharField(
                help_text="IANA timezone. Example: 'America/New_York', 'Europe/London'.",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["is_active", "sort_order"],
                name="GlobalMarke_is_acti_9d5339_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(fields=["status"], name="GlobalMarke_status_4fbf13_idx"),
        ),
        migrations.AddIndex(
            model_name="marketholiday",
            index=models.Index(
                fields=["market", "date"], name="GlobalMarke_market__0ae448_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketholiday",
            index=models.Index(fields=["date"], name="GlobalMarke_date_93d1d6_idx"),
        ),
        migrations.AddConstraint(
            model_name="marketholiday",
            constraint=models.UniqueConstraint(
                fields=("market", "date"), name="uniq_market_holiday_date"
            ),
        ),
        migrations.RunPython(
            code=_populate_market_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="market",
            name="key",
            field=models.SlugField(
                help_text="Stable identifier used by API/WS. Example: 'new_york', 'london', 'tokyo'.",
                max_length=40,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="GlobalMarkets.market",
            ),
        ),
        migrations.DeleteModel(
            name="MarketDataSnapshot",
        ),
        migrations.DeleteModel(
            name="UserMarketWatchlist",
        ),
        migrations.RemoveField(
            model_name="marketholiday",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="marketholiday",
            name="description",
        ),
        migrations.RemoveField(
            model_name="marketholiday",
            name="updated_at",
        ),
        migrations.AddIndex(
            model_name="marketsession",
            index=models.Index(
                fields=["market", "weekday"], name="GlobalMarke_market__eea884_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketsession",
            constraint=models.UniqueConstraint(
                fields=("market", "weekday"), name="uniq_market_session_weekday"
            ),
        ),
    ]
