# Generated by Django 5.2.6 on 2025-12-05 22:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[
                            ("SCHWAB", "Charles Schwab"),
                            ("PAPER", "Paper Trading"),
                        ],
                        default="PAPER",
                        max_length=20,
                    ),
                ),
                ("broker_account_id", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "net_liq",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "stock_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "option_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "day_trading_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_order_id", models.CharField(blank=True, max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                ("asset_type", models.CharField(default="EQ", max_length=8)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MKT", "Market"),
                            ("LMT", "Limit"),
                            ("STP", "Stop"),
                            ("STP_LMT", "Stop Limit"),
                        ],
                        default="LMT",
                        max_length=16,
                    ),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WORKING", "Working"),
                            ("FILLED", "Filled"),
                            ("CANCELED", "Canceled"),
                            ("PARTIAL", "Partially Filled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="WORKING",
                        max_length=12,
                    ),
                ),
                (
                    "time_placed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("time_last_update", models.DateTimeField(auto_now=True)),
                ("time_canceled", models.DateTimeField(blank=True, null=True)),
                ("time_filled", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="ActAndPos.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exec_id", models.CharField(blank=True, max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("exec_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="ActAndPos.account",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="ActAndPos.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, max_length=128)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FUT", "Future"),
                            ("OPT", "Option"),
                            ("FX", "Forex"),
                        ],
                        default="EQ",
                        max_length=8,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("avg_price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "mark_price",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "realized_pl_open",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "realized_pl_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Contract multiplier (e.g. ES=50, CL=1000).",
                        max_digits=18,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="ActAndPos.account",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "symbol", "asset_type")},
            },
        ),
    ]
