# Generated by Django 5.2.6 on 2025-12-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0002_drop_old_account_tables"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Trade",
        ),
    ]
