# Generated by Django 5.2.6 on 2025-12-08 23:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0004_account_paper_balances"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="billing_flat_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Flat subscription charged monthly when billing_plan=Flat.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_performance_pct",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Percent of monthly profits charged when billing_plan=Performance.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="billing_plan",
            field=models.CharField(
                choices=[
                    ("NONE", "No monthly billing"),
                    ("MONTHLY_FLAT", "Flat monthly fee"),
                    ("MONTHLY_PERF", "Monthly performance share"),
                ],
                default="NONE",
                help_text="How Thor bills this account each month.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="commission_flat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Flat commission charged every time an order fills (USD).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="commission_percent_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Percent of notional charged as commission (e.g. 0.005 = 0.5%).",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="commission_scheme",
            field=models.CharField(
                choices=[
                    ("NONE", "No per-order commission"),
                    ("FLAT_PER_ORDER", "Flat fee per order"),
                    ("PCT_NOTIONAL", "Percent of notional value"),
                ],
                default="NONE",
                help_text="Controls the per-order commission Thor charges before executing trades.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="trade_fee_flat",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Additional flat fee applied per fill (reg/clearing/etc).",
                max_digits=10,
            ),
        ),
    ]
