# Generated by ChatGPT on 2025-12-12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0006_account_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                help_text="Owner of this trading account.",
                on_delete=models.deletion.CASCADE,
                related_name="trading_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
