# Generated by Django 5.2.6 on 2025-12-16 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0007_alter_account_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_date", models.DateField(db_index=True)),
                (
                    "net_liq",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "stock_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "option_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "day_trading_buying_power",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_snapshots",
                        to="ActAndPos.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-trading_date", "-captured_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "trading_date"),
                        name="uniq_account_daily_snapshot",
                    )
                ],
            },
        ),
    ]
