# Generated by Django 5.2.6 on 2025-12-17 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0010_account_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
