# Generated by Django 5.2.6 on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0011_alter_account_created_at"),
    ]

    operations = [
        # The production/dev database already has this column in some environments.
        # Make the migration safe in both cases (fresh DB vs existing DB).
        migrations.RunSQL(
            sql=[
                "ALTER TABLE \"ActAndPos_account\" ADD COLUMN IF NOT EXISTS quote_provider varchar(32);",
                "UPDATE \"ActAndPos_account\" SET quote_provider='AUTO' WHERE quote_provider IS NULL;",
                "ALTER TABLE \"ActAndPos_account\" ALTER COLUMN quote_provider SET DEFAULT 'AUTO';",
                "ALTER TABLE \"ActAndPos_account\" ALTER COLUMN quote_provider SET NOT NULL;",
            ],
            reverse_sql=[
                "ALTER TABLE \"ActAndPos_account\" ALTER COLUMN quote_provider DROP NOT NULL;",
                "ALTER TABLE \"ActAndPos_account\" ALTER COLUMN quote_provider DROP DEFAULT;",
                "ALTER TABLE \"ActAndPos_account\" DROP COLUMN IF EXISTS quote_provider;",
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="quote_provider",
            field=models.CharField(
                default="AUTO",
                help_text="Quote provider used to populate balances/positions (legacy DB column).",
                max_length=32,
            ),
        ),
    ]
