# Generated by Django 5.2.6 on 2026-01-11 19:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0012_account_quote_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(default="SCHWAB", max_length=20)),
                ("broker_account_id", models.CharField(db_index=True, max_length=128)),
                ("broker_order_id", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(default="WORKING", max_length=32)),
                ("symbol", models.CharField(max_length=32)),
                ("asset_type", models.CharField(default="EQ", max_length=8)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("order_type", models.CharField(default="LMT", max_length=16)),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("broker_payload", models.JSONField(blank=True, null=True)),
                (
                    "time_placed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("time_last_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_key", models.CharField(db_index=True, max_length=64)),
                (
                    "client_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Client-generated identifier",
                        max_length=64,
                    ),
                ),
                ("symbol", models.CharField(max_length=32)),
                ("asset_type", models.CharField(default="EQ", max_length=8)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MKT", "Market"),
                            ("LMT", "Limit"),
                            ("STP", "Stop"),
                            ("STP_LMT", "Stop Limit"),
                        ],
                        default="LMT",
                        max_length=16,
                    ),
                ),
                (
                    "limit_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WORKING", "Working"),
                            ("FILLED", "Filled"),
                            ("CANCELED", "Canceled"),
                            ("PARTIAL", "Partially Filled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="WORKING",
                        max_length=12,
                    ),
                ),
                (
                    "time_placed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("time_last_update", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(default="SCHWAB", max_length=20)),
                ("broker_account_id", models.CharField(db_index=True, max_length=128)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "net_liq",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "stock_buying_power",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "option_buying_power",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "day_trading_buying_power",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("broker_payload", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "broker", "broker_account_id"),
                        name="uniq_live_balance_user_broker_account",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LiveExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(default="SCHWAB", max_length=20)),
                ("broker_account_id", models.CharField(db_index=True, max_length=128)),
                ("broker_exec_id", models.CharField(blank=True, max_length=128)),
                ("symbol", models.CharField(max_length=32)),
                ("side", models.CharField(max_length=4)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("exec_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="ActAndPos.liveorder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["broker_account_id", "exec_time"],
                        name="idx_live_exec_acct_time",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LivePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker", models.CharField(default="SCHWAB", max_length=20)),
                ("broker_account_id", models.CharField(db_index=True, max_length=128)),
                ("symbol", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, max_length=128)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FUT", "Future"),
                            ("OPT", "Option"),
                            ("FX", "Forex"),
                        ],
                        default="EQ",
                        max_length=8,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "mark_price",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "broker_pl_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "broker_pl_ytd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("broker_payload", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "user",
                            "broker",
                            "broker_account_id",
                            "symbol",
                            "asset_type",
                        ),
                        name="uniq_live_position",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_key",
                    models.CharField(
                        db_index=True,
                        help_text="Client-facing account identifier",
                        max_length=64,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "net_liq",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "buying_power",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "day_trade_bp",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "account_key"),
                        name="uniq_paper_balance_user_account",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_key", models.CharField(db_index=True, max_length=64)),
                ("exec_id", models.CharField(blank=True, max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                ("side", models.CharField(max_length=4)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("exec_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_fills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fills",
                        to="ActAndPos.paperorder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["account_key", "exec_time"],
                        name="idx_paper_fill_acct_time",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_key", models.CharField(db_index=True, max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                ("description", models.CharField(blank=True, max_length=128)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("EQ", "Equity"),
                            ("FUT", "Future"),
                            ("OPT", "Option"),
                            ("FX", "Forex"),
                        ],
                        default="EQ",
                        max_length=8,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "mark_price",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "realized_pl_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "realized_pl_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "account_key", "symbol", "asset_type"),
                        name="uniq_paper_position",
                    )
                ],
            },
        ),
    ]
