# Generated by Django 5.2.6 on 2026-01-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ActAndPos", "0014_migrate_mixed_to_paper_live"),
        ("Trades", "0002_remove_trade_account_remove_trade_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user",
        ),
        migrations.RemoveField(
            model_name="position",
            name="account",
        ),
        migrations.RemoveField(
            model_name="accountdailysnapshot",
            name="account",
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="AccountDailySnapshot",
        ),
    ]
