# Generated by Django 5.2.6 on 2026-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity"),
                            ("FUTURE", "Future"),
                            ("ETF", "ETF"),
                            ("INDEX", "Index"),
                            ("FOREX", "Forex"),
                            ("CRYPTO", "Crypto"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("exchange", models.CharField(blank=True, max_length=32)),
                ("currency", models.CharField(blank=True, default="USD", max_length=8)),
                (
                    "tick_size",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "point_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
