# Generated by Django 5.2.6 on 2026-01-02 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInstrumentWatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "stream",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this symbol should be subscribed on the live feed.",
                    ),
                ),
                ("order", models.IntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlisted_by",
                        to="Instruments.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instrument_watchlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Instrument Watchlist Item",
                "verbose_name_plural": "User Instrument Watchlist Items",
                "indexes": [
                    models.Index(
                        fields=["user", "order"], name="idx_watchlist_user_order"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "instrument"),
                        name="uniq_user_instrument_watchlist_item",
                    )
                ],
            },
        ),
    ]
