# Generated by GitHub Copilot on 2026-01-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0002_userinstrumentwatchlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="quote_source",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto"),
                    ("SCHWAB", "Schwab"),
                    ("TOS", "ThinkOrSwim"),
                ],
                default="AUTO",
                help_text="Which feed should be treated as the source of truth for this symbol.",
                max_length=16,
            ),
        ),
    ]
