# Generated by Django 5.2.6 on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0003_instrument_quote_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Market region (canonical values only)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="display_precision",
            field=models.IntegerField(default=2, help_text="Decimal places to show"),
        ),
        migrations.AddField(
            model_name="instrument",
            name="margin_requirement",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Margin required per contract in USD (if applicable)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
