# Generated by hand to reflect ownership move from ThorTrading -> Instruments.

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0004_instrument_extra_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketTrading24Hour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_group",
                    models.IntegerField(db_index=True, help_text="Shared key with MarketSession.session_number"),
                ),
                ("session_date", models.DateField(db_index=True)),
                ("country", models.CharField(help_text="Market region (canonical values only)", max_length=32)),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Instrument symbol (e.g., ES, YM, NQ, AAPL, SPY)",
                        max_length=32,
                    ),
                ),
                ("prev_close_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("open_price_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("open_prev_diff_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("open_prev_pct_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("low_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("high_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("range_diff_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("range_pct_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("close_24h", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                (
                    "volume_24h",
                    models.BigIntegerField(
                        blank=True, help_text="Cumulative volume across JP→US window", null=True
                    ),
                ),
                ("finalized", models.BooleanField(default=False, help_text="True when US close is reached")),
            ],
            options={
                "managed": False,
                "db_table": "ThorTrading_markettrading24hour",
                "verbose_name": "24-Hour Global Session",
                "verbose_name_plural": "24-Hour Global Sessions",
                "indexes": [models.Index(fields=["session_date", "country", "symbol"], name="idx_mkt24h_date_cty_sym")],
                "unique_together": {("session_group", "country", "symbol")},
            },
        ),
    ]
