# Generated by Django 5.2.6 on 2026-01-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0006_state_add_rtd_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentIntraday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp_minute",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Minute bucket (UTC). Example: 2025-12-26 17:51:00+00:00",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                ("open_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("high_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("low_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("close_1m", models.DecimalField(decimal_places=4, max_digits=18)),
                ("volume_1m", models.BigIntegerField(default=0)),
                (
                    "bid_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "ask_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "spread_last",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Instrument Intraday Bar",
                "verbose_name_plural": "Instrument Intraday Bars",
                "db_table": "ThorTrading_instrumentintraday",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rolling52WeekStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Trading symbol (ES, YM, CL, AAPL, SPY, etc.)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "high_52w",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Highest price in last 52 weeks",
                        max_digits=14,
                    ),
                ),
                (
                    "high_52w_date",
                    models.DateField(help_text="Date when the 52-week high was set"),
                ),
                (
                    "low_52w",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lowest price in last 52 weeks",
                        max_digits=14,
                    ),
                ),
                (
                    "low_52w_date",
                    models.DateField(help_text="Date when the 52-week low was set"),
                ),
                (
                    "last_price_checked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Most recent LAST price that was checked",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "all_time_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="All-time high (optional)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "all_time_high_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when all-time high was set",
                        null=True,
                    ),
                ),
                (
                    "all_time_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="All-time low (optional)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "all_time_low_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when all-time low was set",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "52-Week Stats",
                "verbose_name_plural": "52-Week Stats",
                "db_table": "ThorTrading_rolling52weekstats",
                "ordering": ["symbol"],
                "managed": False,
            },
        ),
    ]
