# Generated by Django 5.2.6 on 2026-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0009_align_instruments_owned_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalstatvalue",
            name="signal",
            field=models.CharField(
                choices=[
                    ("STRONG_BUY", "Strong Buy"),
                    ("BUY", "Buy"),
                    ("HOLD", "Hold"),
                    ("SELL", "Sell"),
                    ("STRONG_SELL", "Strong Sell"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="signalweight",
            name="signal",
            field=models.CharField(
                choices=[
                    ("STRONG_BUY", "Strong Buy"),
                    ("BUY", "Buy"),
                    ("HOLD", "Hold"),
                    ("SELL", "Sell"),
                    ("STRONG_SELL", "Strong Sell"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="instrumentintraday",
                    index=models.Index(
                        fields=["symbol", "timestamp_minute"],
                        name="idx_intraday_instr_sym_ts",
                    ),
                ),
                migrations.AddIndex(
                    model_name="instrumentintraday",
                    index=models.Index(
                        fields=["timestamp_minute"],
                        name="idx_intraday_instr_ts",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="instrumentintraday",
                    constraint=models.UniqueConstraint(
                        fields=("timestamp_minute", "symbol"),
                        name="uniq_intraday_symbol_minute",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=r'''
DO $$
BEGIN
    IF to_regclass('public."Instruments_instrumentintraday"') IS NOT NULL THEN
        CREATE INDEX IF NOT EXISTS idx_intraday_instr_sym_ts
            ON "Instruments_instrumentintraday" ("symbol", "timestamp_minute");

        CREATE INDEX IF NOT EXISTS idx_intraday_instr_ts
            ON "Instruments_instrumentintraday" ("timestamp_minute");

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'uniq_intraday_symbol_minute'
        ) THEN
            ALTER TABLE "Instruments_instrumentintraday"
                ADD CONSTRAINT uniq_intraday_symbol_minute
                UNIQUE ("timestamp_minute", "symbol");
        END IF;
    END IF;
END $$;
''',
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
        ),
    ]
