# Generated by hand to align model field options with current code.

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0013_markettrading24hour_global_symbol_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signalstatvalue",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signal_stat_values",
                to="Instruments.instrument",
            ),
        ),
        migrations.AlterField(
            model_name="contractweight",
            name="instrument",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_weight",
                to="Instruments.instrument",
            ),
        ),
    ]
