# Generated by hand to match InstrumentIntraday Meta options in code.

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Instruments", "0014_rtd_related_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrumentintraday",
            options={
                "managed": True,
                "verbose_name": "Intraday Bar",
                "verbose_name_plural": "Intraday Bars",
            },
        ),
    ]
