# Generated by Django 5.2.6 on 2025-10-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_statement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realaccount",
            name="brokerage_provider",
            field=models.CharField(
                choices=[
                    ("SCHWAB", "Charles Schwab"),
                    ("IB", "Interactive Brokers"),
                    ("TDA", "TD Ameritrade"),
                    ("FIDELITY", "Fidelity"),
                    ("OTHER", "Other Brokerage"),
                ],
                default="SCHWAB",
                help_text="Brokerage provider for this account",
                max_length=30,
            ),
        ),
    ]
