# Generated by Django 5.2.6 on 2025-10-14 15:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_statement", "0002_increase_brokerage_provider_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperaccount",
            name="starting_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10000.00"),
                help_text="Initial virtual balance for paper trading",
                max_digits=15,
            ),
        ),
    ]
