# Generated by Django 5.2.6 on 2025-09-23 03:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futuretrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HbsThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('buy_hi', models.DecimalField(decimal_places=6, max_digits=10)),
                ('buy_lo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sell_lo', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sell_hi', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HBS Threshold',
                'verbose_name_plural': 'HBS Thresholds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_weight', to='futuretrading.tradinginstrument')),
            ],
            options={
                'verbose_name': 'Contract Weight',
                'verbose_name_plural': 'Contract Weights',
                'ordering': ['instrument__symbol'],
            },
        ),
        migrations.CreateModel(
            name='SignalStatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=20)),
                ('value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_stat_values', to='futuretrading.tradinginstrument')),
            ],
            options={
                'verbose_name': 'Signal Statistical Value',
                'verbose_name_plural': 'Signal Statistical Values',
                'ordering': ['instrument__symbol', 'signal'],
                'unique_together': {('instrument', 'signal')},
            },
        ),
    ]
