# Generated by Django 5.2.6 on 2025-09-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futuretrading', '0002_hbsthresholds_contractweight_signalstatvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=20, unique=True)),
                ('weight', models.IntegerField(help_text='Weight value for this signal type (e.g., 2, 1, 0, -1, -2)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Signal Weight',
                'verbose_name_plural': 'Signal Weights',
                'ordering': ['-weight'],
            },
        ),
    ]
