# Generated manually to drop unused tables# Generated by Django 5.2.6 on 2025-10-25 01:29

from django.db import migrations

from django.db import migrations



class Migration(migrations.Migration):

class Migration(migrations.Migration):

    dependencies = [

        ("FutureTrading", "0003_delete_hbsthresholds"),    dependencies = [

    ]        ("FutureTrading", "0003_delete_hbsthresholds"),

    ]

    operations = [

        # Drop tables directly using SQL    operations = [

        migrations.RunSQL(        migrations.RemoveField(

            sql="DROP TABLE IF EXISTS \"FutureTrading_marketdata\" CASCADE;",            model_name="tradingsignal",

            reverse_sql="",  # No reverse - can't recreate data            name="instrument",

        ),        ),

        migrations.RunSQL(        migrations.RemoveField(

            sql="DROP TABLE IF EXISTS \"FutureTrading_tradingsignal\" CASCADE;",            model_name="watchlistitem",

            reverse_sql="",            name="group",

        ),        ),

        migrations.RunSQL(        migrations.AlterUniqueTogether(

            sql="DROP TABLE IF EXISTS \"FutureTrading_watchlistitem\" CASCADE;",            name="watchlistitem",

            reverse_sql="",            unique_together=None,

        ),        ),

        migrations.RunSQL(        migrations.RemoveField(

            sql="DROP TABLE IF EXISTS \"FutureTrading_watchlistgroup\" CASCADE;",            model_name="watchlistitem",

            reverse_sql="",            name="instrument",

        ),        ),

    ]        migrations.DeleteModel(

            name="MarketData",
        ),
        migrations.DeleteModel(
            name="TradingSignal",
        ),
        migrations.DeleteModel(
            name="WatchlistGroup",
        ),
        migrations.DeleteModel(
            name="WatchlistItem",
        ),
    ]
