# Generated by Django 5.2.6 on 2025-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0006_marketopensession_futuresnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketopensession",
            name="ym_entry_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual entry (Ask if buying, Bid if selling)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="ym_high_dynamic",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Entry + 20 points ($100 profit target)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="ym_low_dynamic",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Entry - 20 points ($100 stop loss)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
