# Generated by Django 5.2.6 on 2025-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0013_reorder_future_column"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="futuresnapshot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="futuresnapshot",
            name="session",
        ),
        migrations.AlterModelOptions(
            name="marketopensession",
            options={
                "ordering": ["-captured_at", "future"],
                "verbose_name": "Market Open Session",
                "verbose_name_plural": "Market Open Sessions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="marketopensession",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="ask_size",
            field=models.IntegerField(blank=True, help_text="Ask size", null=True),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="bid_size",
            field=models.IntegerField(blank=True, help_text="Bid size", null=True),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="change",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price change from previous close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="change_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percentage change",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_ask",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ask at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_ask_size",
            field=models.IntegerField(
                blank=True, help_text="Ask size at close", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bid at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_bid_size",
            field=models.IntegerField(
                blank=True, help_text="Bid size at close", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_captured_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of close capture", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_change",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Change at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_change_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Change % at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_instrument_count",
            field=models.IntegerField(
                blank=True, help_text="Instrument count at close (for TOTAL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_last_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Last price at market close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_signal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BUY", "Buy"),
                    ("STRONG_BUY", "Strong Buy"),
                    ("SELL", "Sell"),
                    ("STRONG_SELL", "Strong Sell"),
                    ("HOLD", "Hold"),
                ],
                help_text="Signal at close",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_spread",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Spread at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_status",
            field=models.CharField(
                blank=True,
                help_text="Status at close (e.g., CLOSE TOTAL)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_sum_weighted",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sum weighted at close (for TOTAL)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_volume",
            field=models.BigIntegerField(
                blank=True, help_text="Volume at close", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_vwap",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="VWAP at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_weight",
            field=models.IntegerField(
                blank=True, help_text="Weight at close (for TOTAL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="close_weighted_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="TOTAL weighted average at close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="day_24h_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="24 hour high",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="day_24h_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="24 hour low",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="exit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price when target or stop was hit",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="exit_time",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when outcome was determined", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="instrument_count",
            field=models.IntegerField(
                blank=True,
                default=11,
                help_text="Count of instruments (for TOTAL)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="last_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Last traded price at market open",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="open_vs_prev_number",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Open vs Prev (Number)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="open_vs_prev_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Open vs Prev (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("WORKED", "Worked"),
                    ("DIDNT_WORK", "Didn't Work"),
                    ("NEUTRAL", "Neutral"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                help_text="Trade outcome for this future",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="range_high_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Range (24h High - 24h Low)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="range_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Range as % of previous close",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="spread",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bid-Ask spread",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="status",
            field=models.CharField(
                blank=True, help_text="Status (e.g., LIVE TOTAL)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="sum_weighted",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sum weighted (e.g., 13.02, for TOTAL)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="volume",
            field=models.BigIntegerField(
                blank=True, help_text="Trading volume", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="vwap",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Volume Weighted Average Price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="week_52_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="52-week high",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="week_52_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="52-week low",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="week_52_range_high_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="52-week range (High - Low)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="week_52_range_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="52-week range as % of current price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="weight",
            field=models.IntegerField(
                blank=True, help_text="Weight value (for TOTAL)", null=True
            ),
        ),
        migrations.AddField(
            model_name="marketopensession",
            name="weighted_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="TOTAL weighted average (e.g., -0.109)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="didnt_work",
            field=models.BooleanField(
                default=False, help_text="Trade outcome flag (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="future",
            field=models.CharField(
                choices=[
                    ("TOTAL", "TOTAL Composite"),
                    ("YM", "Dow Jones (YM)"),
                    ("ES", "S&P 500 (ES)"),
                    ("NQ", "NASDAQ (NQ)"),
                    ("RTY", "Russell 2000 (RTY)"),
                    ("CL", "Crude Oil (CL)"),
                    ("SI", "Silver (SI)"),
                    ("HG", "Copper (HG)"),
                    ("GC", "Gold (GC)"),
                    ("VX", "Volatility (VX)"),
                    ("DX", "Dollar Index (DX)"),
                    ("ZB", "Bonds (ZB)"),
                ],
                default="YM",
                help_text="Future symbol for this capture row",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="reference_ask",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ask price at capture",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="reference_bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bid price at capture",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="reference_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous close price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="reference_last",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Reference last traded price (legacy)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="reference_open",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Open price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketopensession",
            name="total_signal",
            field=models.CharField(
                choices=[
                    ("BUY", "Buy"),
                    ("STRONG_BUY", "Strong Buy"),
                    ("SELL", "Sell"),
                    ("STRONG_SELL", "Strong Sell"),
                    ("HOLD", "Hold"),
                ],
                help_text="Signal from TOTAL or individual future",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="marketopensession",
            unique_together={("country", "year", "month", "date", "future")},
        ),
        migrations.DeleteModel(
            name="FutureCloseSnapshot",
        ),
        migrations.DeleteModel(
            name="FutureSnapshot",
        ),
    ]
