# Generated by Django 5.2.6 on 2025-11-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0030_marketsession_rename_reference_ask_to_session_ask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketsession",
            name="reference_bid",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="reference_last",
        ),
        migrations.AddField(
            model_name="marketsession",
            name="session_bid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Bid price at capture (renamed from reference_bid)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketsession",
            name="session_last",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Last traded price at capture (renamed from reference_last)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous close price (renamed from reference_close)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_open",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Open price (renamed from reference_open)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
