# Generated by Django 5.2.6 on 2025-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0040_targethighlowconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketsession",
            name="didnt_work",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="exit_price",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="exit_time",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="fw_exit_percent",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="fw_exit_value",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="fw_nwdw",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="fw_stopped_out_nwdw",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="fw_stopped_out_value",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="fw_weight",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="outcome",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="study_fw",
        ),
        migrations.RemoveField(
            model_name="marketsession",
            name="wndw",
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_close",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous close price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="session_open",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Open price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Configurable target above entry (per TargetHighLowConfig)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketsession",
            name="target_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Configurable stop below entry (per TargetHighLowConfig)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
