# Generated by Django 5.2.6 on 2025-11-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0043_alter_marketsession_buy_didnt_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="wndw",
            field=models.CharField(max_length=20, null=True, blank=True, help_text="Window/outcome label (optional)"),
        ),
    ]
