# Generated by Django 5.2.6 on 2025-11-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0068_rename_day_24h_high_marketsession_high_24h_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketsession",
            old_name="range_high_low",
            new_name="range_diff_24h",
        ),
        migrations.RenameField(
            model_name="marketsession",
            old_name="range_percent",
            new_name="range_pct_24h",
        ),
    ]
