# Generated by Django 5.2.6 on 2025-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0070_merge_20251127_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="low_pct_52",
            field=models.DecimalField(
                max_digits=14,
                decimal_places=4,
                null=True,
                blank=True,
                help_text="Percent above 52-week low relative to current price",
            ),
        ),
    ]
