# Generated by Django 5.2.6 on 2025-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FutureTrading", "0072_remove_marketsession_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsession",
            name="high_pct_52",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Percent below 52-week high relative to current price",
                max_digits=14,
                null=True,
            ),
        ),
    ]
