# Generated by Django 5.2.6 on 2025-09-21 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('timezone_name', models.CharField(max_length=50)),
                ('market_open_time', models.TimeField()),
                ('market_close_time', models.TimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='USMarketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_trading_day', models.BooleanField(default=True)),
                ('holiday_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'US Market Status',
                'verbose_name_plural': 'US Market Status',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('market_year', models.IntegerField()),
                ('market_month', models.IntegerField()),
                ('market_date', models.IntegerField()),
                ('market_day', models.CharField(max_length=3)),
                ('market_time', models.TimeField()),
                ('market_status', models.CharField(max_length=10)),
                ('utc_offset', models.CharField(max_length=10)),
                ('dst_active', models.BooleanField()),
                ('is_in_trading_hours', models.BooleanField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='timezones.market')),
            ],
            options={
                'verbose_name': 'Market Data Snapshot',
                'verbose_name_plural': 'Market Data Snapshots',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['market', '-collected_at'], name='timezones_m_market__86a32a_idx'), models.Index(fields=['market_status'], name='timezones_m_market__38fae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('full_day', models.BooleanField(default=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='timezones.market')),
            ],
            options={
                'verbose_name': 'Market Holiday',
                'verbose_name_plural': 'Market Holidays',
                'ordering': ['date'],
                'unique_together': {('market', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserMarketWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timezones.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Market Watchlist',
                'verbose_name_plural': 'User Market Watchlists',
                'ordering': ['order', 'created_at'],
                'unique_together': {('user', 'market')},
            },
        ),
    ]
