"""
Django settings for thor_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import Config, RepositoryEnv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from repository root (A:\Thor\.env)
ENV_FILE = BASE_DIR.parent / '.env'
config = Config(RepositoryEnv(ENV_FILE)) if ENV_FILE.exists() else Config()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-h=t6s&0w5sb$fcu(0h#^ot6*uexst$i@_hoca74c*h+$n9@#)$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']
# Note: Cloudflare tunnel domains (thor/dev-thor) are added for dev automatically
DEFAULT_TUNNEL_HOSTS = ['thor.360edu.org', 'dev-thor.360edu.org']

# Allow additional hosts via env (comma-separated). Useful for tunnels and staging hosts.
_extra_hosts = [h.strip() for h in config('ALLOWED_HOSTS_EXTRA', default='').split(',') if h.strip()]

# In development, also allow common tunnel domains so callbacks through HTTPS work.
if DEBUG:
    ALLOWED_HOSTS += DEFAULT_TUNNEL_HOSTS

ALLOWED_HOSTS += _extra_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'thor_project.apps.ThorProjectConfig',
    'channels',  # Django Channels for WebSocket support
    'rest_framework',
    'corsheaders',
    'django_filters',
    'users',  # Custom user management with identity & access
    'core',
    'api',
    'ActAndPos.apps.ActandposConfig',
    'Trades.apps.TradesConfig',
    'GlobalMarkets',  # WorldClock and Market data (renamed from 'timezones')
    'thordata',   # Large Excel import app
    'ThorTrading.apps.ThorTradingConfig',  # Modern real-time market data system (keeps legacy DB tables)
    # LiveData - Multi-broker live data pipeline
    'LiveData.schwab.apps.SchwabConfig',  # Schwab OAuth + Trading API
    'LiveData.tos.apps.TosConfig',        # Thinkorswim streaming
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'thor_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'thor_project.context_processors.frontend_base_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'thor_project.wsgi.application'
ASGI_APPLICATION = 'thor_project.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='thor_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        # IMPORTANT: default to 'postgres' inside Docker, override via .env for local
        'HOST': config('DB_HOST', default='postgres'),
        'PORT': config('DB_PORT', default='5432'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Custom User Model
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = 'users.CustomUser'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite development server
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # Vite development server alternate port
    "http://127.0.0.1:5174",
    "https://thor.360edu.org",  # Cloudflare tunnel domain
    "https://dev-thor.360edu.org",  # Secondary Cloudflare tunnel domain
]

CORS_ALLOW_CREDENTIALS = True

# Initialize CSRF trusted origins (Cloudflare tunnel will be added dynamically below)
_default_csrf_origins = [
    'http://localhost',
    'http://localhost:8000',
    'http://localhost:8001',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8001',
    'https://localhost',
    'https://127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = _default_csrf_origins.copy() if DEBUG else []

if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([f'https://{host}' for host in DEFAULT_TUNNEL_HOSTS])

# Allow adding more CSRF trusted origins via env (comma-separated), e.g., https://thor.360edu.org
_csrf_extra = [o.strip() for o in config('CSRF_TRUSTED_ORIGINS_EXTRA', default='').split(',') if o.strip()]
if _csrf_extra:
    CSRF_TRUSTED_ORIGINS.extend(_csrf_extra)

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# Redis Configuration (LiveData shared message bus)
# ============================================================================

# Redis Configuration (live bus)
REDIS_URL = config('REDIS_URL', default='redis://redis:6379/0')

# Redis Configuration (LiveData shared message bus)
REDIS_HOST = config('REDIS_HOST', default='redis')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)

# ============================================================================
# Django Channels Configuration (WebSocket support)
# ============================================================================

# Point Django to the ASGI application
ASGI_APPLICATION = 'thor_project.asgi.application'

# Configure Channels to use Redis as the channel layer backend
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Realtime job providers (plugins loaded by thor_project.realtime.registry)
REALTIME_JOB_PROVIDERS = [
    "GlobalMarkets.realtime.provider",
    "ThorTrading.realtime.provider",
]


# Frontend base URL exposed in admin shortcuts and cross-links
FRONTEND_BASE_URL = config('FRONTEND_BASE_URL', default='http://localhost:5173/')

# ============================================================================
# LiveData - Schwab OAuth Configuration
# ============================================================================

SCHWAB_ENV = (os.getenv("SCHWAB_ENV") or config('SCHWAB_ENV', default='disabled')).strip().lower()
SCHWAB_ENABLED = SCHWAB_ENV in {"dev", "development", "prod", "production"}

# Schwab API credentials (get from Schwab Developer Portal)
SCHWAB_CLIENT_ID = config('SCHWAB_CLIENT_ID', default='')
SCHWAB_CLIENT_SECRET = config('SCHWAB_CLIENT_SECRET', default='')

# Cloudflare Tunnel URL (for HTTPS OAuth callback in dev)
CLOUDFLARE_TUNNEL_URL = config('CLOUDFLARE_TUNNEL_URL', default='')

# Schwab OAuth redirect URI (must match Schwab Developer Portal exactly)
SCHWAB_REDIRECT_URI = config(
    'SCHWAB_REDIRECT_URI',
    default='https://dev-thor.360edu.org/api/schwab/oauth/callback/'
)

if DEBUG and CLOUDFLARE_TUNNEL_URL:
    # Add tunnel domain to allowed hosts and CSRF trusted origins for dev callbacks
    tunnel_domain = CLOUDFLARE_TUNNEL_URL.replace('https://', '').replace('http://', '')
    if tunnel_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(tunnel_domain)
    if CLOUDFLARE_TUNNEL_URL not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(CLOUDFLARE_TUNNEL_URL)

# Structured logging for background supervisors and services
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'ThorTrading': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'thor_project': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'heartbeat': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Only trust proxy-provided HTTPS headers when explicitly enabled
TRUST_PROXY_SSL_HEADERS = config('TRUST_PROXY_SSL_HEADERS', default=not DEBUG, cast=bool)

if TRUST_PROXY_SSL_HEADERS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
else:
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False

# Only force HTTPS in production (not in DEBUG mode for local development)
SECURE_SSL_REDIRECT = False  # Disable HTTPS redirect entirely in dev/prod

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SESSION_COOKIE_SECURE = False  # Allow HTTP cookies in development
CSRF_COOKIE_SECURE = False     # Allow HTTP CSRF cookies in development

