# Generated by GitHub Copilot on 2026-01-02

from django.db import migrations


def forwards(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    CustomUser.objects.filter(role="OWNER").update(is_staff=True, is_superuser=True)


def backwards(apps, schema_editor):
    # We don't automatically revoke superuser/staff on rollback.
    # The intent is to preserve manual changes to these flags.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
