# Generated by Django 5.2.6 on 2025-12-06 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ActAndPos", "0003_delete_trade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exec_id", models.CharField(blank=True, max_length=64)),
                ("symbol", models.CharField(max_length=32)),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("exec_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="ActAndPos.account",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="ActAndPos.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "db_table": "ActAndPos_trade",
            },
        ),
    ]
