# Generated by Django 5.2.6 on 2025-10-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "connection_type",
                    models.CharField(
                        default="internal",
                        help_text="Logical connector type, e.g. excel_rtd, schwab_api, websocket",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_name",),
            },
        ),
        migrations.CreateModel(
            name="ConsumerApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_feed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fallback feed when no explicit assignment is active.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_apps",
                        to="SchwabLiveData.datafeed",
                    ),
                ),
            ],
            options={
                "ordering": ("display_name",),
            },
        ),
        migrations.CreateModel(
            name="FeedAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="If selected, use this feed before others when multiple are enabled.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle to enable/disable this feed for the consumer without deleting the link.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower numbers are preferred when multiple feeds are enabled.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consumer_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="SchwabLiveData.consumerapp",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="SchwabLiveData.datafeed",
                    ),
                ),
            ],
            options={
                "ordering": ("priority", "-is_primary", "feed__display_name"),
                "unique_together": {("consumer_app", "feed")},
            },
        ),
        migrations.AddField(
            model_name="consumerapp",
            name="feeds",
            field=models.ManyToManyField(
                blank=True,
                related_name="consumer_apps",
                through="SchwabLiveData.FeedAssignment",
                to="SchwabLiveData.datafeed",
            ),
        ),
    ]
