# Generated by Django 5.2.6 on 2025-10-11 16:13

from django.db import migrations


def seed_initial_feeds(apps, schema_editor):
    DataFeed = apps.get_model("SchwabLiveData", "DataFeed")
    ConsumerApp = apps.get_model("SchwabLiveData", "ConsumerApp")
    FeedAssignment = apps.get_model("SchwabLiveData", "FeedAssignment")

    excel_feed, _ = DataFeed.objects.get_or_create(
        code="excel_rtd",
        defaults={
            "display_name": "Excel RTD",
            "description": "Live quotes streamed from Excel Real-Time-Data workbook.",
            "connection_type": "excel_rtd",
            "provider_key": "excel_live",
        },
    )

    schwab_feed, _ = DataFeed.objects.get_or_create(
        code="schwab_api",
        defaults={
            "display_name": "Schwab API",
            "description": "Brokerage API delivering equity/option market data.",
            "connection_type": "schwab_api",
            "provider_key": "schwab",
        },
    )

    futures_app, _ = ConsumerApp.objects.get_or_create(
        code="futures",
        defaults={
            "display_name": "Futures Trading",
            "description": "Thor futures dashboard and related services.",
            "default_feed": excel_feed,
        },
    )

    stock_app, _ = ConsumerApp.objects.get_or_create(
        code="stock_trading",
        defaults={
            "display_name": "Stock Trading",
            "description": "Equity trading dashboards and analytics.",
            "default_feed": schwab_feed,
        },
    )

    FeedAssignment.objects.get_or_create(
        consumer_app=futures_app,
        feed=excel_feed,
        defaults={
            "is_primary": True,
            "priority": 10,
            "notes": "Default futures feed from Excel RTD.",
        },
    )

    FeedAssignment.objects.get_or_create(
        consumer_app=stock_app,
        feed=schwab_feed,
        defaults={
            "is_primary": True,
            "priority": 10,
            "notes": "Default equities feed from Schwab API.",
        },
    )


def unseed_initial_feeds(apps, schema_editor):
    DataFeed = apps.get_model("SchwabLiveData", "DataFeed")
    ConsumerApp = apps.get_model("SchwabLiveData", "ConsumerApp")

    ConsumerApp.objects.filter(code__in=["futures", "stock_trading"]).delete()
    DataFeed.objects.filter(code__in=["excel_rtd", "schwab_api"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_initial_feeds, unseed_initial_feeds),
    ]
