# Generated by Django 5.2.6 on 2025-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0002_seed_default_feeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafeed",
            name="provider_key",
            field=models.CharField(
                blank=True,
                help_text="Identifier used by provider_factory to instantiate the backend connector.",
                max_length=64,
            ),
        ),
    ]
