# Generated by Django 5.2.6 on 2025-10-11 16:14

from django.db import migrations


def populate_keys(apps, schema_editor):
    DataFeed = apps.get_model("SchwabLiveData", "DataFeed")
    mapping = {
        "excel_rtd": "excel_live",
        "schwab_api": "schwab",
    }
    for code, provider_key in mapping.items():
        DataFeed.objects.filter(code=code).update(provider_key=provider_key)


def remove_keys(apps, schema_editor):
    DataFeed = apps.get_model("SchwabLiveData", "DataFeed")
    DataFeed.objects.filter(code__in=["excel_rtd", "schwab_api"]).update(provider_key="")


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0003_datafeed_provider_key"),
    ]

    operations = [migrations.RunPython(populate_keys, remove_keys)]
