# Generated by Django 5.2.6 on 2025-10-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0004_populate_provider_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumerapp",
            name="authorized_capabilities",
            field=models.JSONField(
                default=list, help_text="Auto-populated based on app registry"
            ),
        ),
        migrations.AlterField(
            model_name="consumerapp",
            name="code",
            field=models.SlugField(
                help_text="Must be one of the predefined Thor applications",
                max_length=64,
                unique=True,
            ),
        ),
    ]
