# Generated by Django 5.2.6 on 2025-10-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0005_add_dropdown_validation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumerapp",
            name="default_feed",
        ),
        migrations.RemoveField(
            model_name="consumerapp",
            name="feeds",
        ),
        migrations.AddField(
            model_name="consumerapp",
            name="fallback_feed",
            field=models.ForeignKey(
                blank=True,
                help_text="Fallback feed if primary fails",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fallback_consumers",
                to="SchwabLiveData.datafeed",
            ),
        ),
        migrations.AddField(
            model_name="consumerapp",
            name="primary_feed",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary data feed for this consumer app",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_consumers",
                to="SchwabLiveData.datafeed",
            ),
        ),
    ]
