# Generated by Django 5.2.6 on 2025-10-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SchwabLiveData", "0007_set_default_feeds"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FeedAssignment",
        ),
    ]
