# Generated by Django 5.2.6 on 2025-09-21 23:12

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_trades', models.IntegerField(db_index=True, help_text='Number of trades')),
                ('dlst', models.CharField(db_index=True, help_text='DLST identifier', max_length=50)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('date', models.IntegerField(db_index=True)),
                ('day', models.CharField(max_length=20)),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, help_text='Opening price', max_digits=15, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, help_text='Closing price', max_digits=15, null=True)),
                ('volume', models.BigIntegerField(blank=True, db_index=True, help_text='Trading volume', null=True)),
                ('world_net_change', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('world_net_perc_change', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('world_high', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('world_low', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('additional_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='All other trading indicators and AI data stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', '-date'],
                'indexes': [models.Index(fields=['year', 'month', 'date'], name='thordata_tr_year_e7b839_idx'), models.Index(fields=['dlst', 'year', 'month'], name='thordata_tr_dlst_371253_idx'), models.Index(fields=['no_trades'], name='thordata_tr_no_trad_5dcbe3_idx'), models.Index(fields=['volume'], name='thordata_tr_volume_89ebb2_idx')],
                'unique_together': {('no_trades', 'dlst', 'year', 'month', 'date')},
            },
        ),
    ]
